### ISSUE TITLE
XPS 9370 Developer Edition compatibility

### ISSUE THREAD

**Issue by paulobrien** [Boltgolt/howdy#10]
Hi!

I am trying to test Howdy on the Dell XPS 13 9370 Developer Edition (Ubuntu 16.04), and although the install detects and tries 2 cameras, neither turn on the IR emitters (which work in Windows obviously).

Any thoughts on what might cause this or how I can help debug?

Thanks!

**Comment by Boltgolt** [comment]
I suspect that some integrated camera's are not wired the same as mine are. Mine is recognized as 2 separate USB cameras and the IR camera also automatically controls the emitters. It could be that a separate command has to be send to the device for the emitters to work.

A similar issue has been reported as #6, and i did some digging there. However, i don't have enough C experience with linux to try it.
