### ISSUE TITLE
howdy - corrupted size vs. prev_size

### ISSUE THREAD

**Issue by diepes** [boltgolt/howdy#106]
_Please describe the issue in as much detail as possible, including any errors and traces_

```
Traceback (most recent call last):
  File "/lib/security/howdy/compare.py", line 11, in <module>
    import cv2
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 77: invalid continuation byte
Unknown error: -11
```
```
$ sudo howdy -U TheUser clear
This will clear all models for TheUser
Do you want to continue [y/N]: y
Models cleared
```
```
$ sudo howdy test
corrupted size vs. prev_size
Aborted
```

apt - purge package howdy and dependancy's
apt - install howdy
lot of installing, pip updating and compiling

At end of re-install it asked to update /etc/pam.d/comon-auth, adding a duplicate Howdy config.

Re-add user, and it works, do get a error, but it proceeds.
e.g.
```
$ sudo ls
VIDIOC_QUERYCTRL: Input/output error
Identified face as TheUser
```
Working again.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu 16.04

Howdy version: 2.4.0

**Comment by boltgolt** [comment]
You have some very broken build of OpenCV there. All those errors point to low level C issues. As long as Howdy is working fine it's not a problem, but there could be some issues with the build environment for cv2. 

As Howdy is still working i'm closing this for now, but if anyone has the same problem feel free to add a comment.
