### ISSUE TITLE
How do I install howdy in /lib/security?

### ISSUE THREAD

**Issue by ryankhart** [boltgolt/howdy#108]
In the README.md, it says this:
> To minimize the chance of this program being compromised, it's recommended to leave Howdy in /lib/security and to keep it read-only.

I'm not a very advanced Linux user yet, so I would just be installing Linux programs from the given terminal commands like `sudo apt install`. I did some googling around for how to move programs to a different directory, but I'm not confident I understand it right.

Could someone please update the README.md with step-by-step instructions for how to install howdy in /lib/security, preferably in command line?

**Comment by boltgolt** [comment]
The debian installer automatically puts [all files](https://github.com/boltgolt/howdy/blob/master/debian/install) related to Howdy into `/lib/security`, so no need to move them. I've chosen to keep this sentence in the readme to hopefully deter people from moving it manually out of `/lib` to `/opt` for instance, but it might be creating more confusion than actually helping.
