### ISSUE TITLE
No howdy command

### ISSUE THREAD

**Issue by abrad1212** [Boltgolt/howdy#11]
After installing there is no `howdy` command on my cmd.

I installed this a few mins ago on my new laptop with Ubuntlu
After installing there is no `howdy`...

**Comment by Boltgolt** [comment]
The issue here is a permission issue with permissions of the executable on installation. Use `sudo` to get around it for now.

**Comment by Boltgolt** [comment]
Fixed on the dev branch, thanks for reporting!
