### ISSUE TITLE
Python TypeError: __call__(): incompatible function arguments. 

### ISSUE THREAD

**Issue by VanVan** [boltgolt/howdy#110]
`sudo howdy add` 

Adding face model for the user vanvan
Enter a label for this new model [Initial model]: vanvan
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Please look straight into the camera
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 90, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 117, in <module>
    enc = face_recognition.face_encodings(frame)
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 199, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 153, in _raw_face_landmarks
    face_locations = _raw_face_locations(face_image)
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: dlib.fhog_object_detector, image: array, upsample_num_times: int=0) -> dlib.rectangles

Invoked with: <dlib.fhog_object_detector object at 0x7f95e1186c00>, None, 1

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu 18.10 64bits
Brand new linux installation

Installed via ppa:boltgolt/howdy

**Comment by boltgolt** [comment]
The real error here is `VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV`, which is a common problem with IR cameras that only have a grey image mode. A fix (using ffmpeg as recorder) is currently available on the dev branch but probably won't be released for at least a few weeks. Take a look at #105 for further discussion.
