### ISSUE TITLE
Turns on flash instead of IR Emitter

### ISSUE THREAD

**Issue by bhanu6599** [Boltgolt/howdy#12]
During installation, when it starts the camera check, the camera flash is turned on instead of the IR Emitter. When I answer the question "Did your IT Emitters turned on?" as no, it says no suitable IR camera found. Also, 
"The directory '/home/bhanu6599/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag."
is shown before the camera check.

**Comment by Boltgolt** [comment]
That simply means you don't have a suitable IR camera. Only cameras that implement the IR component as a separate video device can be picked up by howdy. 

If you want to help us support your webcam you can take a look at #6.
