### ISSUE TITLE
Face Unlock not working after explicit locking the screen in Linux Mint

### ISSUE THREAD

**Issue by itsgauravjain22** [boltgolt/howdy#121]
_Please describe the issue in as much detail as possible, including any errors and traces_
Howdy works well for terminal application on my Dell Inspiron 7560 laptop with only camera.
But there's issue with gui version of linux mint lock screen. At first login, howdy detects the face and give the option of login after verifying the face, but text similar to "Face Recognised" message is displayed with ugly placement. I would suggest after verifying face, it must automatically login to desktop.

Second after first login, If I lock the screen explicitly, then howdy doesn't recognise the face, even my camera light blinks. This was tested numerously by me in all identical situations, where howdy used to work.

Linux distribution (if applicable): Linux Mint 19 Cinnamon Edition
Howdy version: Latest version

**Comment by boltgolt** [comment]
Could your run `sudo howdy config` and set no_confirmation to `true`? Also check that end_report has been set to `false`.

Are there any errors in `/var/log/auth.log`?

**Comment by itsgauravjain22** [comment]
I am unaware of howdy config. Thanks for the help. It solved the problem of not login after the explicit log off the laptop. But tthe above mentioned comment is a bug with set `no_confirmation` to `true`.

I have uploaded below my `/var/log/auth.log` for further information
[gaurav-auth.log](https://github.com/boltgolt/howdy/files/2748464/gaurav-auth.log)

**Comment by boltgolt** [comment]
Unfortunately this is a problem with the way the screensavers handle PAM conversations, good to hear the fix worked though!

**Comment by haakon8855** [comment]
How did you solve this?

**Comment by sethjt33** [comment]
Hello, at first I was not able to get howdy to start on the lock screen however, after making these changes it starts now and the camera comes on but it fails every time to unlock from the lock screen.  All other application of howdy works perfectly with exception of the lock screen.  does anyone have any ideas?

**Comment by chukynax** [comment]
same thing here, ubuntu xfce4 desktop, light-locker 
Mar 23 09:33:52 dell /lib/security/howdy/pam.py[10210]: Traceback (most recent call last):
Mar 23 09:33:52 dell /lib/security/howdy/pam.py[10210]:   File "/lib/security/howdy/pam.py", line 93, in pam_sm_authenticate
Mar 23 09:33:52 dell /lib/security/howdy/pam.py[10210]:     return doAuth(pamh)
Mar 23 09:33:52 dell /lib/security/howdy/pam.py[10210]:   File "/lib/security/howdy/pam.py", line 39, in doAuth
Mar 23 09:33:52 dell /lib/security/howdy/pam.py[10210]:     pamh.conversation(pamh.Message(pamh.PAM_TEXT_INFO, "Attempting face detection"))
Mar 23 09:33:52 dell /lib/security/howdy/pam.py[10210]: PamException: Conversation error

**Comment by jkatnik** [comment]
Hi @boltgolt in 2023 :)

is there any progress regarding unlocking Mint (21.1) from the screensaver?
It works in Ubuntu 22, so maybe there is a way to make it run in Mint too?

**Comment by egavazzi** [comment]
@jkatnik @SeidlEnt [This comment](https://github.com/boltgolt/howdy/issues/28#issuecomment-396231042) worked for me on Mint 21.2 :)
