### ISSUE TITLE
howdy didn't work with gui Apps

### ISSUE THREAD

**Issue by jamy3531** [boltgolt/howdy#123]
_Please describe the issue in as much detail as possible, including any errors and traces_

Howdy works fine in terminal every time, but failed in Gui apps, Gparted, screen unlock for example.
Howdy worked very well for all applications before last update(the latest version).

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Deepin Linux

Howdy version: 2.5.0

**Comment by jamy3531** [comment]
The camera light blinks but verification can not passed for gui applications

**Comment by boltgolt** [comment]
Could you try running `sudo howdy config` and setting no_confirmation to `true`?

**Comment by jamy3531** [comment]
@boltgolt I did so, but it made no difference

**Comment by boltgolt** [comment]
Are there any python errors in `/var/log/auth.log`?

**Comment by jamy3531** [comment]
There's no such file in my system.

Strangely， everything’s ok again after my deepin system update.

**Comment by boltgolt** [comment]
`/var/log/auth.log` is used to log authentication errors on all debian distro's i've seen so far, so that's weird. Good to hear it's somehow fixed though, i'll mark it as closed for now. Don't be afraid to reopen it if you have the same issues again.

**Comment by boulchci** [comment]
I open the issue because the same problem happened to me. When I open the log file the only error is `[HOWDY]: Failure, timeout reached`.
Is there any solution ?
