### ISSUE TITLE
Howdy cannot find "dlib"

### ISSUE THREAD

**Issue by Lasklo** [boltgolt/howdy#124]
When I try to run `sudo howdy add`, it outputs this:

`Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 101, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 9, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'`

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux Mint 19.1Tessa

Howdy version:
Newest Version from apt repository.

**Comment by Lasklo** [comment]
Fixed by reinstalling with all dependencies, after that dlib compiled correctly.

**Comment by boltgolt** [comment]
Thanks for posting the solution before i could!

**Comment by marcemira** [comment]
Hello! Can I have the list of dependencies I need to install please? are these pip or regular apt packages? thanks

**Comment by MorenoMdz** [comment]
How long does it take to instal dlib? With `pip3 install dlib` it stays in "installing" for a very long time...

**Comment by boltgolt** [comment]
Long, but not longer than an hour

**Comment by MorenoMdz** [comment]
It crashed into a perm error here, I will need to search for a more Mint specific install guide.
