### ISSUE TITLE
[Security] Ask for a password if howdy did not run for some period of time

### ISSUE THREAD

**Issue by jardev** [boltgolt/howdy#125]
Check when pam.py was last time used for authentication and if it was longer than some period of time (configured in config.ini, 24 hours by default), then `sys.exit(0)`. Before that touch a file something like `/lib/security/howdy/.lastrun` and use it check last run time. This should increase the security level.

**Comment by boltgolt** [comment]
First of all, thanks a lot for the suggestion!

I've always said Howdy isn't a secure way of logging in, just a more convenient one. This doesn't mean i don't take security seriously but i do want to keep ease of use as one of the highest priorities. Having the user enter a password every day for a very small bump in security just isn't worth it in my opinion.

I'll keep an open mind though, and if more people want this i'll add it to the list for 2.6.0.
