### ISSUE TITLE
Disable Howdy only for initial sing-in

### ISSUE THREAD

**Issue by wout** [boltgolt/howdy#141]
I would like to be able to disable howdy for the initial log in process. Logging in with howdy does not unlock the keychain, which forces me to enter my password manually every time I need to make a ssh connection involving a ssh key. This can be avoided only when I do the initial login with password. But in order to do so, there is a significant time to wait until the password can be entered, while howdy is trying to get my face recognized.

**Comment by boltgolt** [comment]
First of all, thanks for the suggestion! I agree with you that unlocking they keyring every time is a nuisance. There are ways to keep it [unlocked permanently](https://github.com/boltgolt/howdy/issues/56#issuecomment-405862123), but they are very insecure.

However, as explained [here](https://github.com/boltgolt/howdy/issues/85#issuecomment-432444371), Howdy does not know _why_ it is being called. The PAM call comes with no context. Detecting a first login would therefore have to rely on logging previous Howdy sessions or monitoring shutdowns. Both of which i would rather not do. Would getting #9 to work be a reasonable compromise?

**Comment by wout** [comment]
Thanks for your prompt reply. And of course thanks for this excellent package, which I use a lot on a daily basis. :)

What's suggested in #9 seems like the ideal compromise. If I can start typing my password during face recognition, that would solve my issue completely. Then it's up to me to keep my face out of reach of the camera.

**Comment by boltgolt** [comment]
I'll close this for now to keep this topic in #9

**Comment by Thalhammer** [comment]
You can work around this by temporarily disabling howdy during first login.
I am using elementary OS 5 which is based on Ubuntu (18.04 i believe) but it should work similar in other distros.
NOTE: "dominik" is my username and should get replaced with your own.
What I did was first create a file `/etc/sudoers.d/howdy` to allow executing howdy without a password.
`dominik ALL = (ALL) NOPASSWD: /usr/local/bin/howdy`
This is required for the following.

Create a task to run after login. I did not bother to look where to best place it as elementary os provides a nice gui for this. Make it execute the following command:
`/usr/bin/sudo /usr/local/bin/howdy disable 0`

Create a override in systemd to disable howdy before login. I picked "systemd-logind.service" as its a perfect fit, but it does not really matter which one you use as long as it is done before your login screen appears.
Create the file `/etc/systemd/system/systemd-logind.service.d/override.conf` and add the following:
`[Service]
ExecStartPre=+-/bin/bash -c "SUDO_USER=dominik /usr/local/bin/howdy disable 1"`

After a reboot it should work fine. Howdy is disabled until you login using your password which causes your keychain to be unlocked, and enabled for subsequent logins (like after standby or for sudo). This is the behaviour I wanted.

This could also be interesting for:
#234 

NOTE: All of this is not a proper solution but the best I came up with without error prone changes to howdy. It might break with updates to howdy or your OS, so don't rely on it.

**Comment by eric1932** [comment]
I found that in howdy's configuration file, there is an option called "disabled." Maybe you can achieve the goal by changing this option. eg. disable howdy before shutdown, and enable it right after user's login

**Comment by ryanerwin** [comment]
I would also definitely prefer to use Howdy as "screen unlock" rather than login... Mostly because of the keychain password issue.

@boltgolt said:
> Howdy does not know why it is being called. The PAM call comes with no context. Detecting a first login would therefore have to rely on logging previous Howdy sessions or monitoring shutdowns

From the context that Howdy is called under are you able to interact with the rest of the system?

If so, what if Howdy checks to see if a desktop environment exists via something like `loginctl` to see if the user already has a session (thus we're 99% sure it's a screen lock)?

**Comment by lichaar** [comment]
This will be a really helpful enhancement, If I'm going to re-enter my password for keyring on every login, There is no point of using Howdy anymore :cry:

**Comment by KairuiLiu** [comment]
For KDE, there is a sample way
only config `/etc/pam.d/kde`, do not add line in \*system\* and \*login\*
then it can only work on after you lock...

**Comment by RokeJulianLockhart** [comment]
> [`#issuecomment-459777566`](https://github.com/boltgolt/howdy/issues/141#issuecomment-459777566)

@boltgolt, how would one request that the developers of PAM inform something, like Howdy, of the purpose of its invocation? ([`linux-pam/linux-pam/issues/new`](https://github.com/linux-pam/linux-pam/issues/new)?)

**Comment by lynxnb** [comment]
@KairuiLiu 
> For KDE, there is a sample way only config `/etc/pam.d/kde`, do not add line in *system* and *login* then it can only work on after you lock...

Is there anything similar for GNOME?

**Comment by Racle** [comment]
Created (with help of an AI) a quick script to do this automatically. 
It's based on @Thalhammer [solution](https://github.com/boltgolt/howdy/issues/141#issuecomment-553326878).
Little extra security to enable just disable command without sudo.

Tested on Ubuntu 24.04 (Gnome with Wayland) and `Howdy 3.0.0 BETA`

You can find script here: https://gist.github.com/Racle/fa873fbaf05e6d3f06618de3d5b6f865
