### ISSUE TITLE
Auto detect if camera is already in use. 

### ISSUE THREAD

**Issue by VanishingTacos** [boltgolt/howdy#144]
If the camera is already in use howdy will hang forever until the camera is no longer in use. Howdy should detect if the camera is already in use and automatically prompt to ask for a password.

**Comment by boltgolt** [comment]
Good catch, i'll add a check in 2.6.0

**Comment by VanVan** [comment]
Right, also even if the camera is in use, but if there is a driver or hardware problem, it should wait a short amount of time, and stop after that, and asking password. Maybe a config file to configure the amount of time and how many attempts is done can be a good way to work on different hardware and let the user change default value if needed

**Comment by boltgolt** [comment]
Was hard to implement consistently, bumping to next release

**Comment by pankaj4u4m** [comment]
I will try to work on it in a branch.

**Comment by boltgolt** [comment]
@pankaj4u4m that would be much appreciated!

**Comment by pankaj4u4m** [comment]
Hi, sorry,
What exactly should be done here?

In current installation I get error message and immediately get to enter password.

I started cheese app then
sudo apt update
Failed to read camera specified in your 'device_path', aborting
Unknown error: 1
[sudo] password for pankaj:

So I think it is already working as intended?

**Comment by boltgolt** [comment]
Possibly, there have been a lot of code changes since 2 years ago so it might have already been fixed accidentally. Thanks for looking into it!

**Comment by VanishingTacos** [comment]
It's been so long that my current laptop does not have an IR camera to test!
