### ISSUE TITLE
Can't add face or use test command - ubuntu 18.04 - Dell XPS 13 (9370)

### ISSUE THREAD

**Issue by theChoseone94** [boltgolt/howdy#149]
I have just installed Howdy on my XPS 13 9370. During the install process the infrared camera lit up and the terminal asked if they were on and I chose yes. The rest of the install process went fine. 
I tried to set up my face, with "sudo howdy add" and then got the response:

VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 101, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 109, in <module>
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

My debugging skills are pretty low, so I don't know what the error might be and what might fix it. 

---

Linux distribution (if applicable): Ubuntu 18.04

Howdy version: 2.5

**Comment by boltgolt** [comment]
Take a look at #88
