### ISSUE TITLE
Timeout never reached

### ISSUE THREAD

**Issue by kmizzi** [boltgolt/howdy#150]
I've been trying to get this to work and I'm not having any luck.

At first the sudo howdy test returned a grey output.  I fixed this by setting:
force_mjpeg = true

Now the sudo howdy test activates the IR camera, and the test shows black and white, but there is never any time out or confirmation that user is added.

I experimented with higher dark threshold and certainty as well with no luck!

**Comment by boltgolt** [comment]
You probably have too many dark frames. Set `dark_threshold` to 100 in `sudo howdy config`.

**Comment by kmizzi** [comment]
Awesome this fixed it!
