### ISSUE TITLE
How does one set number of cores in the python calls

### ISSUE THREAD

**Issue by yfaykya** [Boltgolt/howdy#16]
I see the face_recognition cli has an option to set number of cores. I was wondering is this exposed somewhere? Would be nice to have as option in config.ini.
I will have a look myself later.

PS. Really nice work!

**Comment by Boltgolt** [comment]
That's great addition! You seem to have already looked into it, so if you want to implement it in a pull request that would be really helpful. If not i'll implement it, but it will take a little longer.

**Comment by Boltgolt** [comment]
You're right, and i don't really fancy implementing my own multithreading. Thanks for the suggestion either way though!
