### ISSUE TITLE
Installation not working on elementaryos 5.0 (Debian)

### ISSUE THREAD

**Issue by pixeline** [boltgolt/howdy#162]
After a (apparently) successful installation, running 'howdy' in the terminal shows this error message

> sudo: howdy: command not found

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): 
elementary OS 5.0
Howdy version: 2.5

**Comment by pixeline** [comment]
on ElementaryOS, I needed to do `sudo apt-get install software-properties-common` before `sudo add-apt-repository ppa:boltgolt/howdy`

**Comment by boltgolt** [comment]
Thanks for figuring it out!

@rileyball would installing `software-properties-common`also enable PPAs for vanilla debian?

**Comment by belosthomas** [comment]
Same issue on Pop!_OS 19.04. Command not found.
`sudo apt-get install software-properties-common` solved nothing for me.

**Comment by rileyball** [comment]
@belosthomas @boltgolt You shouldn't enable PPAs on Debian. Doing so is typically called making a "franken-debian" and does more harm than good to your system.
