### ISSUE TITLE
in compare.py : No module name cv2

### ISSUE THREAD

**Issue by Sanjay126** [boltgolt/howdy#164]
I have checked and opencv2 version 4.0.1 is installed for both python2 andpython3 yet this issue arises when we need sudo access in terminal. login part is working fine.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): ubuntu 18.04.02

Howdy version: 2.5.0

**Comment by boltgolt** [comment]
What does the following command return?

```
sudo /usr/bin/env python3 -c "import cv2; print(cv2.__version__);"
```

**Comment by Sanjay126** [comment]
4.0.1

**Comment by boltgolt** [comment]
Looks like you have an functioning openCV install and python3 bindings, but they're called incorrectly. Could you try replacing `"/usr/bin/python3"` with `"/usr/bin/env", "python3"` on line 33 in `/lib/security/howdy/pam.py`?

**Comment by Sanjay126** [comment]
Actually I solved it. I ran pip install opencv-python inside compare.py(because error was in that file) once and then removed it.
Thanks for help

**Comment by CybernetiX-S3C** [comment]
I am having this issue.

sudo /usr/bin/env python3 -c "import cv2; print(cv2.__version__);"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'cv2'

Yet with python version 2.7

sudo /usr/bin/env python -c "import cv2; print(cv2.__version__);"

4.0.0


Kali Linux 2019.1
Debian Distro
Python Versions:
[ CybernetiX-S3C howdy ]# python -V
Python 2.7.16rc1
[ CybernetiX-S3C howdy ]# python3 -V
Python 3.5.6

**Comment by boltgolt** [comment]
Did you run `pip3 install opencv-python`?

**Comment by CybernetiX-S3C** [comment]
Of course I did. I also went to the website to install 4.0 manually from
sources.

**Comment by NescobarAlopLop** [comment]
for me installing opencv worked, but not with pip and specifically for python3:
`sudo apt-get install python3-opencv`

**Comment by Zocker1999NET** [comment]
Then the issue introduced by @CybernetiX-S3C, and solved by @NescobarAlopLop should be fixed by adding `python3-opencv` to the dependencies of the debian package. Because the package is available in the repositories of Debian (since buster) and Ubuntu (since 19.10 eoan) this should be no problem for current users and make the installation easier for new users.

**Comment by CybernetiX-S3C** [comment]
It is available. That is correct. But my error remains. I'd like to also
get rid of the whole not being able to use root.

John Poli Modica
Cyber Security Professional
CybernetiX S3C
https://CybernetiX-S3C.net/

**Comment by CybernetiX-S3C** [comment]
Also, as a reminder, I am using the latest Kali Linux with everything up to
date.

John Poli Modica
Cyber Security Professional
CybernetiX S3C
https://CybernetiX-S3C.net/
