### ISSUE TITLE
Dosen't work on Mint Cinamon 19 dlib issue 

### ISSUE THREAD

**Issue by Zenek-Hastro** [boltgolt/howdy#168]
I have installed all correctly, but when i try to run "sudo howdy add", terminal give to me an error:

```
zenek@zenek:~$ sudo howdy add
Traceback (most recent call last):
  File "/lib/security/howdy/compare.py", line 18, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'
Unknown error: 1
[sudo] password for zenek:         
No module named 'dlib'

Can't import the dlib module, check the output of
pip3 show dlib
```

I already have tryed to install the dlib and dosent work ... can someone help me ?

**Comment by boltgolt** [comment]
What's the output of `pip3 show dlib`?

**Comment by KaitenIV** [comment]
Nothing, just return zenek$zenek.

Thanks for reply!

Il mar 12 mar 2019, 14:09 boltgolt <notifications@github.com> ha scritto:

**Comment by boltgolt** [comment]
Could run `pip3 install dlib` and try `sudo howdy add` after that?

**Comment by KaitenIV** [comment]
zenek@zenek:~$ pip3 install dlib
Collecting dlib
  Using cached
https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-install-6gh5_61l/dlib/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/tmp/pip-record-tjggz1so/install-record.txt
--single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.6.7 (default, Oct 22 2018, 11:32:17)
    Invoking CMake setup: 'cmake
/tmp/pip-install-6gh5_61l/dlib/tools/python
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-6gh5_61l/dlib/build/lib.linux-x86_64-3.6
-DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.7")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.2.2
    -- Using CMake version: 3.10.2
    -- Compiling dlib version: 19.17.0
    -- SSE4 instructions can be executed by the host processor.
    -- AVX instructions can be executed by the host processor.
    -- Enabling AVX instructions
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Looking for XOpenDisplay in
/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
    -- Looking for XOpenDisplay in
/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so -
found
    -- Looking for gethostbyname
    -- Looking for gethostbyname - found
    -- Looking for connect
    -- Looking for connect - found
    -- Looking for remove
    -- Looking for remove - found
    -- Looking for shmat
    -- Looking for shmat - found
    -- Looking for IceConnectionNumber in ICE
    -- Looking for IceConnectionNumber in ICE - found
    -- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
    -- Looking for png_create_read_struct
    -- Looking for png_create_read_struct - found
    -- Looking for jpeg_read_header
    -- Looking for jpeg_read_header - found
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Checking for module 'lapack'
    --   Found lapack, version 0.2.20+ds
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Found OpenBLAS library
    -- Looking for sgetrf_single
    -- Looking for sgetrf_single - found
    -- Using OpenBLAS's built in LAPACK
    -- Looking for cblas_ddot
    -- Looking for cblas_ddot - found
    -- Looking for sgesv
    -- Looking for sgesv - not found
    -- Looking for sgesv_
    -- Looking for sgesv_ - not found
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR
CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at
least version "7.5")
    -- DID NOT FIND CUDA
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- C++11 activated.
    -- Configuring done
    -- Generating done
    -- Build files have been written to:
/tmp/pip-install-6gh5_61l/dlib/build/temp.linux-x86_64-3.6
    Invoking CMake build: 'cmake --build . --config Release -- -j2'
    Scanning dependencies of target dlib
    [  2%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
    [  2%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
    [  3%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
    [  4%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
    [  5%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
    [  6%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
    [  8%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
    [  9%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
    [ 10%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
    [ 11%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
    [ 12%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
    [ 13%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
    [ 15%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
    [ 16%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
    [ 17%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/filtering/kalman_filter.cpp.o
    [ 18%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/test_for_odr_violations.cpp.o
    [ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/svm/auto.cpp.o
    [ 20%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
    [ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
    [ 23%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
    [ 24%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
    [ 25%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
    [ 26%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
    [ 27%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
    [ 29%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
    [ 30%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
    [ 31%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
    [ 32%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
    [ 33%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
    [ 34%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
    [ 36%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
    [ 37%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
    [ 38%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
    [ 39%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
    [ 40%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
    [ 41%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
    [ 43%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
    [ 44%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
    [ 45%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
    [ 46%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
    [ 47%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
    [ 48%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/threads/async.cpp.o
    [ 50%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
    [ 51%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
    [ 52%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/cuda/cpu_dlib.cpp.o
    [ 53%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/cuda/tensor_tools.cpp.o
    [ 54%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/fonts.cpp.o
    [ 55%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/widgets.cpp.o
    [ 56%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/drawable.cpp.o
    [ 58%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/canvas_drawing.cpp.o
    [ 59%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/style.cpp.o
    [ 60%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_widgets/base_widgets.cpp.o
    [ 61%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_1.cpp.o
    [ 62%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/gui_core/gui_core_kernel_2.cpp.o
    [ 63%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
    [ 65%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
    [ 66%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
    [ 67%] Building CXX object
dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
    [ 68%] Linking CXX static library libdlib.a
    [ 68%] Built target dlib
    Scanning dependencies of target dlib_python
    [ 69%] Building CXX object CMakeFiles/dlib_python.dir/src/dlib.cpp.o
    [ 70%] Building CXX object CMakeFiles/dlib_python.dir/src/matrix.cpp.o
    [ 72%] Building CXX object CMakeFiles/dlib_python.dir/src/vector.cpp.o
    [ 73%] Building CXX object
CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o
    [ 74%] Building CXX object
CMakeFiles/dlib_python.dir/src/svm_rank_trainer.cpp.o
    [ 75%] Building CXX object
CMakeFiles/dlib_python.dir/src/decision_functions.cpp.o
    [ 76%] Building CXX object CMakeFiles/dlib_python.dir/src/other.cpp.o
    [ 77%] Building CXX object CMakeFiles/dlib_python.dir/src/basic.cpp.o
    [ 79%] Building CXX object CMakeFiles/dlib_python.dir/src/cca.cpp.o
    [ 80%] Building CXX object
CMakeFiles/dlib_python.dir/src/sequence_segmenter.cpp.o
    [ 81%] Building CXX object
CMakeFiles/dlib_python.dir/src/svm_struct.cpp.o
    [ 82%] Building CXX object CMakeFiles/dlib_python.dir/src/image.cpp.o
    [ 83%] Building CXX object CMakeFiles/dlib_python.dir/src/image2.cpp.o
    [ 84%] Building CXX object CMakeFiles/dlib_python.dir/src/image3.cpp.o
    [ 86%] Building CXX object CMakeFiles/dlib_python.dir/src/image4.cpp.o
    [ 87%] Building CXX object
CMakeFiles/dlib_python.dir/src/rectangles.cpp.o
    [ 88%] Building CXX object
CMakeFiles/dlib_python.dir/src/object_detection.cpp.o
    [ 89%] Building CXX object
CMakeFiles/dlib_python.dir/src/shape_predictor.cpp.o
    [ 90%] Building CXX object
CMakeFiles/dlib_python.dir/src/correlation_tracker.cpp.o
    [ 91%] Building CXX object
CMakeFiles/dlib_python.dir/src/face_recognition.cpp.o
    [ 93%] Building CXX object
CMakeFiles/dlib_python.dir/src/cnn_face_detector.cpp.o
    [ 95%] Building CXX object
CMakeFiles/dlib_python.dir/src/global_optimization.cpp.o
    [ 95%] Building CXX object
CMakeFiles/dlib_python.dir/src/image_dataset_metadata.cpp.o
    [ 96%] Building CXX object
CMakeFiles/dlib_python.dir/src/numpy_returns.cpp.o
    [ 97%] Building CXX object CMakeFiles/dlib_python.dir/src/line.cpp.o
    [ 98%] Building CXX object CMakeFiles/dlib_python.dir/src/gui.cpp.o
    [100%] Linking CXX shared module
/tmp/pip-install-6gh5_61l/dlib/build/lib.linux-x86_64-3.6/
dlib.cpython-36m-x86_64-linux-gnu.so
    [100%] Built target dlib_python
    running install_lib
    copying build/lib.linux-x86_64-3.6/dlib.cpython-36m-x86_64-linux-gnu.so
-> /usr/local/lib/python3.6/dist-packages
    error: could not create '/usr/local/lib/python3.6/dist-packages/
dlib.cpython-36m-x86_64-linux-gnu.so': Permission denied

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools,
tokenize;__file__='/tmp/pip-install-6gh5_61l/dlib/setup.py';f=getattr(tokenize,
'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
/tmp/pip-record-tjggz1so/install-record.txt
--single-version-externally-managed --compile" failed with error code 1 in
/tmp/pip-install-6gh5_61l/dlib/

Il giorno mer 13 mar 2019 alle ore 16:48 boltgolt <notifications@github.com>
ha scritto:

**Comment by boltgolt** [comment]
Don't forget the sudo at the start: `sudo pip3 install dlib`

**Comment by KaitenIV** [comment]
Finally fix it !

Il mer 13 mar 2019, 16:48 boltgolt <notifications@github.com> ha scritto:

**Comment by faliure** [comment]
I was missing g++ to install dlib. So...

sudo apt-get install build-essential
sudo pip3 install dlib
sudo howdy add -U my_user

**Comment by karanjot21** [comment]
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Please look straight into the camera
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 89, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 147, in <module>
    gsframe = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_lib_security_howdy_cli.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 89, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 147, in <module>
    gsframe = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by kiyokodyele** [comment]
> I was missing g++ to install dlib. So...
> 
> sudo apt-get install build-essential
> sudo pip3 install dlib
> sudo howdy add -U my_user

Worked for me running Linux Mint 19 w/ Logitech Brio

**Comment by pwozniak89** [comment]
Thank @faliure that helps me !

**Comment by agridev** [comment]
Helllo 
Thank you for this app
I succeeded to install after following all the recommendation as I got the same errors.
I am newbie in Linux envir :)
I run the add for face and  the cam is working and adding face.
The problem that when logging the cam is on and seems flashing my face but there is no longin, I need to add my password to log to my session.
Please advise 
thanks

**Comment by pwozniak89** [comment]
Hi, @agridev 
Try to add multiple capture of your face with **howdy add**
Be careful with backlight when camera is recognizing you (lot's of failure for me when a window is behind me)
Does it works when you run sudo on command line ?

**Comment by agridev** [comment]
> Hi, @agridev
> Try to add multiple capture of your face with **howdy add**
> Be careful with backlight when camera is recognizing you (lot's of failure for me when a window is behind me)
> Does it works when you run sudo on command line ?

Hi @pwozniak89 
Thank you for the reply.
Yes I added a lot of faces by the sudo command to add.
I do not understand what do you mean by "Does it works when you run sudo on command line ?" does this mean when adding faces? 
Yes it works to add faces, it works to detect faces when authorization to add software or any other authentification request needed, but only thing not working is logging to sessions.
bests 

P.S I am not so expert in command line and linux I am back to linux since year and would like to forget windows (the only thing that makes me installing windows is formatting issues for word documents when exchanged with thirdparties)

**Comment by Gerlo5** [comment]
> > I was missing g++ to install dlib. So...
> > sudo apt-get install build-essential
> > sudo pip3 install dlib
> > sudo howdy add -U my_user
> 
> Worked for me running Linux Mint 19 w/ Logitech Brio

Worked for me too (Linux Mint 19.3 w/ HP Zbook, dlib-19.20.0).
(btw) great work!
