### ISSUE TITLE
Spreading the word

### ISSUE THREAD

**Issue by Leviathan220** [Boltgolt/howdy#17]
Wasn't sure how to email you. I made a post about the project on the Level1 forums [https://forum.level1techs.com/t/windows-hello-style-authentication-for-ubuntu/126171](https://forum.level1techs.com/t/windows-hello-style-authentication-for-ubuntu/126171). if you don't already know who they are you should totally go check them out they are great. Also if you wanted to add anything to my post feel free. I tried to make a joke but up to you if you find the humor in it.

**Comment by Boltgolt** [comment]
Thanks so much for taking the time to do this! Reading your forum post has honestly made my day. Howdy was originally intended as a very simple script for just me to use, but seeing it getting installed in the wild is amazing. Again, thanks for hanging around!

**Comment by Leviathan220** [comment]
Hey software is all about the community especially in open source. I mean I have really enjoyed playing around with this for various authentication types. There are plenty of people who I could see wanting something like this but maybe don't have all the know how to do it themselves.
