### ISSUE TITLE
Ubuntu 18 not working test

### ISSUE THREAD

**Issue by AMV007** [boltgolt/howdy#173]
MSI GS63vr7rf.
during installation selected 'y'
all installed ok, but test not working.

$ sudo howdy test

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

QObject::moveToThread: Current thread (0x2d71ea0) is not the object's thread (0x2e03a20).                                             
Cannot move to target thread (0x2d71ea0)

Segmentation fault

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ununtu 18

Howdy version: latest

**Comment by boltgolt** [comment]
Please use the search function before posting a new issue, this same issue (with a solution) has already been posted over at #54
