### ISSUE TITLE
[FEDORA 29] Problem with howdy add

### ISSUE THREAD

**Issue by BedoM** [boltgolt/howdy#174]
_Please describe the issue in as much detail as possible, including any errors and traces_

Hey ! 

[mabed@legiony520 /]$ sudo howdy add
[sudo] Mot de passe de mabed : 
Data files have not been downloaded, please run the following commands:

	cd /usr/lib64/security/howdy/dlib-data
	sudo ./install.sh

[mabed@legiony520 /]$ cd /usr/lib64/security/howdy/dlib-data
bash: cd: /usr/lib64/security/howdy/dlib-data: No such file or directory
[mabed@legiony520 /]$ sudo ./install.sh
sudo: ./install.sh : commande introuvable

What is the problem ?

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): fedora latest stable

Data files have not been downloaded, please run the following commands:

Linux legiony520 4.20.16-200.fc29.x86_64 #1 SMP Thu Mar 14 15:10:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Howdy version:

**Comment by miba358** [comment]
> _Please describe the issue in as much detail as possible, including any errors and traces_
> 
> Hey !
> 
> [mabed@legiony520 /]$ sudo howdy add
> [sudo] Mot de passe de mabed : 
> Data files have not been downloaded, please run the following commands:
> 
> ```
> cd /usr/lib64/security/howdy/dlib-data
> sudo ./install.sh
> ```
> 
> [mabed@legiony520 /]$ cd /usr/lib64/security/howdy/dlib-data
> bash: cd: /usr/lib64/security/howdy/dlib-data: No such file or directory
> [mabed@legiony520 /]$ sudo ./install.sh
> sudo: ./install.sh : commande introuvable
> 
> What is the problem ?
> 
> I've searched for similar issues already, and my issue has not been reported yet.
> 
> Linux distribution (if applicable): fedora latest stable
> 
> Data files have not been downloaded, please run the following commands:
> 
> Linux legiony520 4.20.16-200.fc29.x86_64 #1 SMP Thu Mar 14 15:10:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> 
> Howdy version:

It looks like the fedora installer doesn't place the dlib-data directory in there. You can clone the repo and copy the folder /src/dlib-data to /usr/lib64/security/howdy and then run the install script for the time being. This should download the needed data files

**Comment by boltgolt** [comment]
Ideally the folder should be included in the installer and the download script should be run automatically. @luyatshimbalanga is that possible for the fedora release?

**Comment by luyatshimbalanga** [comment]
@boltgolt I'll take a look

**Comment by m-ryals** [comment]
it may be helpful to include that in this situation, face id is using the data files which have been downloaded in all other situations, but it is only erroring with i3lock.

**Comment by luyatshimbalanga** [comment]
@BedoM 
Could you test the updated Fedora version? The missing dlib-data should be installed.

**Comment by BedoM** [comment]
Yes no problem

**Comment by luyatshimbalanga** [comment]
Lets close this issue as the fix is in place.

**Comment by boltgolt** [comment]
Thanks for the fix @luyatshimbalanga!
