### ISSUE TITLE
Freenect2 Support

### ISSUE THREAD

**Issue by Stark003** [boltgolt/howdy#175]
Support for Microsoft Kinect v2 IR

**Comment by boltgolt** [comment]
Is the Kinect implemented as a V4L camera device? (does it show up in `v4l2-ctl --list-devices`?)

**Comment by Stark003** [comment]
No, 

it responds with 
```
Failed to open /dev/video0: No such file or directory
```

I have libreenect2 installed and am able to access the various streams when using the premade examples that come with the program.
The kinect's video camera is also not recognised as a video device so I am also unable to use it as a webcam for my pc.

**Comment by boltgolt** [comment]
In that case Kinect support will have to be written as a serperate recorder. I'm not going to be actively working on this, but if someone wants to implement it i will merge it.
