### ISSUE TITLE
Module cv2

### ISSUE THREAD

**Issue by Zml99** [Boltgolt/howdy#18]
File "/lib/security/howdy/compare.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Boltgolt** [comment]
You might have the same problem as @magarto, could you try the fix he found [here](https://github.com/Boltgolt/howdy/issues/7#issuecomment-368305023)?

**Comment by Zml99** [comment]
Thanks for the help. Now work.
