### ISSUE TITLE
Can I skip "enter"?

### ISSUE THREAD

**Issue by shjanken** [boltgolt/howdy#184]
#First of all, Sorry for my poor English.

I use `manjaro cinnamon edition`.

I have installed `howdy` in my system. I can use my face on login screen.But I have to click the "enter" button to login actual.

Can I auto login the system when 'howdy' identified my face?

**Comment by boltgolt** [comment]
This used to be a feature, but was removed in the last release because of dangerous misbehavior and concerns over calling sudo (see #170). You can rollback to version 2.5.0 which still has `dismiss_lockscreen` as config option.
