### ISSUE TITLE
Facial recognition on Zenbook 14 UX433FN

### ISSUE THREAD

**Issue by PeppaPigHS** [boltgolt/howdy#198]
I have tried to add my face using IR camera but when I run sudo howdy add, it doesn't seem to recognize my face unless I am close enough, which is too close compared to Windows Hello. When I run sudo howdy test, it drew black circle around my face without being very close to the IR camera. How to fix this problem?

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu 18.04.2

Howdy version: 2.5.1

**Comment by boltgolt** [comment]
Either your camera isn't good enough, or the image is too noisy. Run `sudo howdy config` and up the "certainty" value, this will make howdy accept more fuzy matches.
