### ISSUE TITLE
No face detected, aborting

### ISSUE THREAD

**Issue by DanMossa** [boltgolt/howdy#202]
_Please describe the issue in as much detail as possible, including any errors and traces_

I type `sudo howdy -U daniel add`
and then leave the label for the new model blank

I then get the error

> No face detected, aborting

So I type `sudo howdy test` and this is what I see

![image](https://user-images.githubusercontent.com/10294777/57295290-03e4e200-707f-11e9-8773-03fbfb9d8126.png)

----

I've searched for similar issues already, and I think https://github.com/boltgolt/howdy/issues/158 is talking about the same issue

Linux distribution (if applicable): Linux Mint 19.1

Howdy version: I believe 2.5.1

I have a Lenovo Thinkpad x1 carbon 6th generation

**Comment by boltgolt** [comment]
Thanks for looking around, but i think #147 is very similar to you (the noise in the screenshots is almost exactly the same) and already includes a solution. If trying different resolutions does not work, let me know.
