### ISSUE TITLE
System program problem detected

### ISSUE THREAD

**Issue by bingws** [boltgolt/howdy#204]
There is  a bug, Once the system rebooted , the system(Ubuntu16.04) will always report the following tip:

![image](https://user-images.githubusercontent.com/10806595/57430955-ddcc6700-7263-11e9-97af-350d82445fdc.png)

![image](https://user-images.githubusercontent.com/10806595/57431161-7cf15e80-7264-11e9-9db4-65a27404b69f.png)

**Comment by boltgolt** [comment]
Is it actually a Howdy issue? This program, apport, triggers on a whole bunch of programs.

**Comment by boltgolt** [comment]
As long as Howdy functions correctly, there's not much of a problem. You can remove the `apport` package if you want to hide the prompts.
