### ISSUE TITLE
Face detection timeout reached

### ISSUE THREAD

**Issue by klascano** [Boltgolt/howdy#22]
hi, 

Great work, but, i have to add new face profile often, i know what happen. if you need information i would like to help.

**Comment by klascano** [comment]
Face detection timeout reached

**Comment by Boltgolt** [comment]
Have you ever had an successful howdy authentication?

**Comment by klascano** [comment]
yes, but each day i have to update my face profile to work.

**Comment by Boltgolt** [comment]
Your camera might not be good enough for realiable face detection, could you try to set the `certainty` to 5 with `sudo howdy config`?

**Comment by Boltgolt** [comment]
Any progress on this one?

**Comment by klascano** [comment]
Hi!

yes, i changed certainty = 5 and i work great, however, i noticed that when you dont watch directly to the camera and the light is poor its fails the login.

One important issue that i have is when a gui app require root permission and the face detection fails, the root pass dialog doesnt appear so the app freeze for ever for example when you install virtualbox additions the main app wait ...........

Thanks, Great Job!

**Comment by Boltgolt** [comment]
Good to hear. GUI prompts _should_ fall back to a password field, does `gksudo ls` work after a timeout?

**Comment by klascano** [comment]
nope, it doesnt work, no appear password promnt dialog. terminal wait forever.
![image](https://user-images.githubusercontent.com/5074068/39629471-f4775a20-4f71-11e8-90cf-8c8129c60e96.png)

**Comment by Boltgolt** [comment]
I think this might be a duplicate of #29, are you using an IR camera?
