### ISSUE TITLE
cannot install in ubuntu 19

### ISSUE THREAD

**Issue by binaryatlas** [boltgolt/howdy#223]
So i cannot add the ppa. It takes forever and finally says "Error: retrieving gpg key timed out."

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): ubuntu 19

Howdy version:

**Comment by boltgolt** [comment]
There's quite a height chance that it's not an issue with Howdy, but with Launchpad. Try it again tomorrow.

**Comment by binaryatlas** [comment]
did and cant find ir during install

**Comment by aapit** [comment]
FWIW, I am on Ubuntu 19.04 and although I'm having some installation issues with the Howdy package itself, I can add the `ppa` without any issues.
