### ISSUE TITLE
sudo howdy test give me error

### ISSUE THREAD

**Issue by klascano** [Boltgolt/howdy#23]
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x3200010

**Comment by Boltgolt** [comment]
Try adding

```
QT_X11_NO_MITSHM=1
```

to /etc/environment (`sudo nano /etc/environment`)

**Comment by Boltgolt** [comment]
Did this one work too?

**Comment by klascano** [comment]
yes, i was an qt error, i google it and i solved, thanks.
