### ISSUE TITLE
Setting for only Login

### ISSUE THREAD

**Issue by mjlabe** [boltgolt/howdy#234]
Would it be possible to only use Howdy for login and disable it for sudo or is that not possible due to the same issue as #85?

**Comment by boltgolt** [comment]
You could manually add Howdy to files in `/etc/pam.d/` that you want to use it for, but not in the `sudo` file. For example, in my case i could add it to `lightdm-greeter` to only use Howdy on the login screen.

This requires you to remove the default installed PAM config by running

```
rm /usr/share/pam-configs/howdy
pam-auth-update --package
```

**Comment by mjlabe** [comment]
Thanks! I'll give it a try.

**Comment by abkiran** [comment]
Have tried? @mjlabe any feedback?

**Comment by mjlabe** [comment]
I didn't try.
