### ISSUE TITLE
How to create List[numpy.ndarray[(rows,cols,3),uint8]] for compute_face_descriptor?

### ISSUE THREAD

**Issue by sushil-bharati** [boltgolt/howdy#236]
Here is what I tried but failed:

```
face_list = []
shape_list = dlib.full_object_detections()
for img in dir:
    shape = sp(img, box)
    face_chip = dlib.get_face_chip(img, shape)
    face_list.append(face_chip)
    shape_list.append(shape)
descs = facerec.compute_face_descriptor(face_list, shape_list)
```

Assuming each `img` has 1 face only and `box` is calculated using `detector(img,1)`

Error I receive is :
`TypeError: compute_face_descriptor(): incompatible function arguments`

**Comment by boltgolt** [comment]
Not sure, this outside of the scope of a Howdy issue
