### ISSUE TITLE
IR blasters not working

### ISSUE THREAD

**Issue by minzukas** [boltgolt/howdy#246]
Camera itself turns on but red side lights don't. Works on windows though. Loggin therefore difficult in low light which leads to typing in password. sudo howdy test functions, have circle around my face. Also tends to somehow forget face after disabling Login keyring.
ubuntu 18.04.3

**Comment by boltgolt** [comment]
Are you using the IR camera, not the normal webcam? Most accurate way to find out is probably to try to use the `test` command in the dark.
