### ISSUE TITLE
Success Report: Razer Blade 17 (2019) - Pop OS 19.04

### ISSUE THREAD

**Issue by adamhill** [boltgolt/howdy#251]
Since there isnt a place to report sucesses...

I installed Howdy successfully on:

**Razer Blade** 17 (2019)
**Pop OS** 19.04
**NVidia** Drivers 435.21
**Kernel:** Linux 5.0.0-1018-oem-osp1 x86_64 (for AX200 Wifi support)

IR installation test went fine the first time.
Added a few models of my face in various lighting conditions.
Has been working fine so far.

Thanks!

**Comment by boltgolt** [comment]
Thanks for the positive feedback!
