### ISSUE TITLE
Number of hits per model?

### ISSUE THREAD

**Issue by faloi** [boltgolt/howdy#257]
Hi there. I'm still understanding how Howdy works, and it would be nice to know which models are being used and which not.

By now, I have 5 models:
* front, with glasses;
* front, without glasses;
* front, with glasses and strong background light;
* side left;
* side right.

I tried setting `end_report = true` but it indeed breaks some UI apps. I imagine some kind of log I can analyse after a few days testing could do the trick.

Any ideas?

**Comment by boltgolt** [comment]
I'd like to add more logging as a whole, this would be a good start. See #226 for logging images
