### ISSUE TITLE
Install problem on Lenovo X390 Yoga IR blasters not working

### ISSUE THREAD

**Issue by pczekalski** [boltgolt/howdy#261]
First of all, thanks for your effort bringing new features to the Linux!

While installing for Lenovo Yoga X390 I've got problem transmitters not triggering at all on any of four configurations. Only RGB camera seems to work (got white LED presenting it on) but no IR beam. Any hints on how to make it work are highly appreciated.

The OS is Ubuntu 19.04

I believe my IR camera is under /dev/video2 (there are total four, even are cameras, odd video capture devices, whatever it means). The resulting output for v4l2-ctl is:

```
N317-PC07:~$ v4l2-ctl -d /dev/video2 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
Type: Video Capture

	[0]: 'GREY' (8-bit Greyscale)
		Size: Discrete 640x360
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.033s (30.000 fps)

```
```
v4l2-ctl -d /dev/video2 --all
Driver Info:
	Driver name      : uvcvideo
	Card type        : Integrated Camera: Integrated I
	Bus info         : usb-0000:00:14.0-8
	Driver version   : 5.0.21
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (Camera 8: ok)
Format Video Capture:
	Width/Height      : 640/360
	Pixel Format      : 'GREY' (8-bit Greyscale)
	Field             : None
	Bytes per Line    : 640
	Size Image        : 230400
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 640, Height 360
	Default     : Left 0, Top 0, Width 640, Height 360
	Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 640, Height 360, Flags: 
Selection: crop_bounds, Left 0, Top 0, Width 640, Height 360, Flags: 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
```

**Comment by pczekalski** [comment]
Some more information:
`v4l2-ctl -d /dev/video2 --all
Driver Info:
	Driver name      : uvcvideo
	Card type        : Integrated Camera: Integrated I
	Bus info         : usb-0000:00:14.0-8
	Driver version   : 5.0.21
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (Camera 8: ok)
Format Video Capture:
	Width/Height      : 640/360
	Pixel Format      : 'GREY' (8-bit Greyscale)
	Field             : None
	Bytes per Line    : 640
	Size Image        : 230400
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 640, Height 360
	Default     : Left 0, Top 0, Width 640, Height 360
	Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 640, Height 360, Flags: 
Selection: crop_bounds, Left 0, Top 0, Width 640, Height 360, Flags: 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
`

**Comment by pczekalski** [comment]
I've got some progress, both cameras work /dev/video0 (RGB) and /dev/video2 (IR) using `fswebcam.` IR camera gives 640x360 (assume it is correct) but still, no IR blasters working.

**Comment by DavidM42** [comment]
Got the same problem on my Lenovo Yoga S740

**Comment by PetePriority** [comment]
@pczekalski This might be related to #269. Could you try if the workaround https://github.com/boltgolt/howdy/issues/269#issuecomment-548105971 works for you?

**Comment by pczekalski** [comment]
Checked, still no luck.
I've set up Windows guest (Ubuntu 19.04 host) on VirtualBox and under the Windows 10 guest, Windows Hello works well. Wireshark installed on the host side but I'm stuck with configuring it as there is no "USB" interface in the options. Any hints on where to start configuration for sniffing?
Thanks in advance.

**Comment by PetePriority** [comment]
> Checked, still no luck.
> I've set up Windows guest (Ubuntu 19.04 host) on VirtualBox and under the Windows 10 guest, Windows Hello works well. Wireshark installed on the host side but I'm stuck with configuring it as there is no "USB" interface in the options. Any hints on where to start configuration for sniffing?
> Thanks in advance.

You need to load the `usbmon` kernel module: `modprobe usbmon`

**Comment by pczekalski** [comment]
Thx,

OK - did a dump. In my case, it is a **usbmon1** interface. However, I still don't get it if usbmon1 is a single device or a bunch of them connected to the bus. If suspect the second case as it seems to capture many devices: 1.4.0, 1.4.1, 1.5.0 and 1.5.2 (as showed up when loaded to wireshark). Any hints, how to filter to the particular device?

**Comment by boltgolt** [comment]
Both this and #269 are about Lenovo cameras and debugging the issue with USB messages, so marking this as a duplicate to keep the discussion in one place
