### ISSUE TITLE
login by fingerprint reader

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [boltgolt/howdy#272]
Hi guys,
really love Howdy and it is working great on my DELL XPS 15 7590.
Is it possible to add fingerprint reader support - to configure face or finger?

Most modern laptops have fingerprint readers, or there are tons of usb devices out there to plug in.

thanks

**Comment by boltgolt** [comment]
Although it's a good succestion, there are some really good implementations outside of Howdy already. Take a look at [fingerprint-gui](https://launchpad.net/~fingerprint/+archive/ubuntu/fingerprint-gui), which i used years ago

**Comment by Jorgen-VikingGod** [comment]
Thx for the hint. I will try it out. 
Thought - it would be great to handle it by the same tool...
