### ISSUE TITLE
Different behavior in classification of dark frames in add.py/compare.py vs test.py

### ISSUE THREAD

**Issue by PetePriority** [boltgolt/howdy#275]
When adjusting the `dark_threshold` parameter then verification with `test.py` leads to different results than `add.py` or `compare.py`. For instance, frames that are valid in `test.py` might be considered too dark in `add.py`/`compare.py`

----

I've searched for similar issues already, and my issue has not been reported yet.

Howdy version: Commit b49bde1

**Comment by boltgolt** [comment]
Fixed in your PR, thanks for your contributions!
