### ISSUE TITLE
Issues Xubuntu 19.10

### ISSUE THREAD

**Issue by AradielSabathius** [boltgolt/howdy#278]
_Please describe the issue in as much detail as possible, including any errors and traces_

When install howdy, I got installation errors related to python3 pip.
You must setup and install correctly python3 pip to get Howdy running correctly.
So, solving the python3 issue, you can install properly Howdy.

Other issues detected.

After install howdy succesfully, at boot, it goes directly to login prompt instead login window and keeps me at the command prompt after loging correctly by face recognition. So I must to start manually the window manager.

When accessing areas like GTK+ LightDM configuration, if the face recognized is not correct, appears a window error where if you click CANCEL, you access anyway to the program.

In other areas like "Window login setup" of XFCE4, after face recognition does nothing and don't let me in the area. Webcam light turn on and off and nothing else happen.

On command line if I write directly command "su", shows "No face model known" and ask for password.
Why I cannot use "su" command after install Howdy?

After install Howdy, "mugshot" app stuck on getting a picture from the camera. This does not happen when Howdy is not installed.

Back from black screen when screen saver is on, in the login window from the screen saver, camera light turn on but keeps in that window so I must acces with password only.
Shows "Password: Unknown error: 1"

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Xubuntu 19.10

Howdy version: 2.5.1

**Comment by in1t3r** [comment]
Answer on the `su` related error. When you are adding the face to the recognition system it is added as your user by default and can be changed with `--user` or `-U` flag. But still by now cannot be added to root. When you are invoking su - which stands for substitute user command -  without parameters it default to trying to log in as root which then invokes a pam.d modules related to root account and not your own. 
Adding faces to root can be added as option as its just another user on platform.
Currently if you want to login as root you can run the substitute user do command
sudo su - 
which will log you in based on face authentication.

Hope I answered your question at least about su.
