### ISSUE TITLE
add command never ends

### ISSUE THREAD

**Issue by macio97** [boltgolt/howdy#284]
Hey, installed your program, ran `sudo howdy add`, inserted the label name and then it never ends working, and the IR camera never lights up.

System: Ubuntu 18.04.3 64bit
Notebook: ASUS Zenbook 14 (https://www.asus.com/us/Laptops/ASUS-ZenBook-14-UX433FN)

![Screenshot](https://user-images.githubusercontent.com/8861988/68994729-a24fcc80-0886-11ea-924a-ab956176a558.png)

**Comment by boltgolt** [comment]
See #248
