### ISSUE TITLE
Howdy CLI not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by NtsikaMngoma** [boltgolt/howdy#286]
I am looking to setup howdy on Ubuntu Bionic Beaver but the command is not recognized after a successful installation. I am quite confused what the issue might be. It outputs:

```
howdy: command not found 
```
and when I run `whereis howdy,` it shows the .gz path

----

Linux distribution (if applicable): Ubuntu 18.04

Howdy version: 2.5.1

**Comment by M0Rph3U56031769** [comment]
how did you install it? I got this error:
Attempting installation of missing data files
Downloading 3 required data files...
Unpacking...
bzip2: Can't open input file *.bz2: No such file or directory.
Error while running last command

**Comment by boltgolt** [comment]
Did you install it from the PPA?

---

@M0Rph3U56031769 That's a different issue, retry the installation and open a new issue if it persists

**Comment by thhart** [comment]
This is what I get in an Ubuntu 19.10. It is from the ppa. Dlib compile goes ok. Camera is detected but finally fails to create the execute. Looks like a problem in pip3:

```
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
Error while running last command
dpkg: error processing package howdy (--configure):
 installed howdy package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.8.7-3) ...
Errors were encountered while processing:
 howdy
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by boltgolt** [comment]
@thhart That's also a completely different problem, see #227 and please use the search function if possible

Closing as it's attracting unrelated issues and the OP has not responded

**Comment by yimisunrise** [comment]
@NtsikaMngoma 
I have the same problem ，I've tried to reinstall it many times and still do 。
Have you finally solved it ？

**Comment by matifali** [comment]
This worked for me
```
sudo apt remove howdy
sudo pip3 install --upgrade pip
sudo dpkg --install howdy_2.6.0.deb
```

**Comment by gaoshuai** [comment]
great
