### ISSUE TITLE
Had to uninstall; without normal password entry simultaneous to face recognition it's not worth it. 

### ISSUE THREAD

**Issue by papermache** [boltgolt/howdy#289]
_Please describe the issue in as much detail as possible, including any errors and traces_

Please solve https://github.com/boltgolt/howdy/issues/9 so reliability can improve independent from productivity.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):

Howdy version:

**Comment by boltgolt** [comment]
Please do not make threads like this, it doesn't help anybody.
