### ISSUE TITLE
Timeout never reached

### ISSUE THREAD

**Issue by Tkopic001** [Boltgolt/howdy#29]
Hello,

I really love your work, this really speeds up auth by a bunch. I have to say, In well lit conditions it gets my face in less then a second so I've put the scan timeout to 2 sec, 

but I've noticed something when i'm in a darker room and there's no way to see the face. It get's stuck and never hits the timeout to offer the password input until I turn on the lights , and then i do it says the timeout has been reached and offers me to input my password. i left it hanging for a few minutes. but nothing happened until i turned on the light and it could see the face. 
I've played a lot with the settings to try to avoid this, but no progress so far,

Maybe you could program a little failsafe if the frame is to dark that it just skips the scan completely? 
i wish i knew python so i could fix this myself and not bother you with this.

Thanks for reading this, 
and keep up the good work!
Cheers!

**Comment by Tkopic001** [comment]
OK, so even though i have absolutely no experience with python code i took the time and read each line of the code you wrote, (Tanks for commenting so much, really helped me to figure it out)
and i've managed to fix this issue for myself, now this is nowhere near a production solution but it did the trick.

I turned on the debugging mode and checked how fast does it really work.
did a few tests with different lighting and it recognizes the face in 1 or max 3 frames.

so just after the loop starts i simply did this in this file:
**/lib/security/howdy/compare.py**
```
...
 # Start the read loop
frames = 0
while True:
        # Increment the frame count every loop
        frames += 1

        **#Fix the timeout issue
        if dark_tries > 10:
                stop(11)**
...
```

And this works pretty well actually. it worked for me, but i hope this helps. 
Have in mind that i have set the dark_threshold to 10.

**Comment by Tkopic001** [comment]
Hello,

I'm glad i could help! :), I work as a SysAdmin so i do have some programing experience with Bash and i can read what PHP code does but i can't write it. I never read or wrote anything in Python. but then again it was really well documented so it was easy to see and understand what each part does. 

I'm using a normal laptop webcam(BisonCam, NB Pro to be precise), it has no IR lights, but Howdy works perfectly fine with it, The only problem I had  were the dark frames, sometimes i use the laptop with the lid closed and connected to the external monitor so the webcam can't see anything and howdy was just stuck waiting so i had to open the lit a little for it to get some light and exit.
 
Now it works like I wanted it to, if there are too many dark frames it means the lid is closed or i'm in the dark so there's no point in trying to find a face and it just exits so that the PAM can ask for a password,  simple.

**Comment by Boltgolt** [comment]
Ah, okay, i do have to warn you that using a normal camera is much less secure (a printout of you with an inkjet printer would be enough to fool it). 
I'll implement a fix where dark frames also check if the timeout has occurred so it should timeout after the 2 seconds you've set. You'll see this appear in your update manager at some point.

**Comment by Jerezano** [comment]
I concur!


-- 
Best Regards;
Hector Roman Jerezano
[image: skype:hjerezano?call]

**Comment by Tkopic001** [comment]
Oh, and i forgot to say, 
I experimented with a few values and it works best if i set my timeout to 5 frames
and set the dark_threshold to 70

**/lib/security/howdy/compare.py** on line **~88**
```
...
         #Fix the timeout issue
        if dark_tries > 5:
                stop(11)
...
```

**/lib/security/howdy/config.ini** on line **40**
```
...
dark_threshold = 70
...
```
