### ISSUE TITLE
Can't use any function

### ISSUE THREAD

**Issue by dan0705** [boltgolt/howdy#297]
![Screenshot from 2019-12-23 10-55-25](https://user-images.githubusercontent.com/28641821/71335001-13b02880-2573-11ea-8677-e98882513873.png)

I don't know exactly what are these problems.
* sudo howdy add: no face detected, aborting
* sudo howdy test: a grey screen
* I'm using Lenovo Ideapad 500 Isk.
Please help! :((

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): 18.04 LTS

Howdy version: The newest version, I've installed it on Dec 22nd, 2019

**Comment by boltgolt** [comment]
What's the full output in the terminal?

**Comment by dannySOLO** [comment]
The screenshot I made was all of the output when I ran "test".
The camera lights were on, but no function worked.

**Comment by boltgolt** [comment]
Okay, what was the full output in your terminal (text cut off in your screenshot)

**Comment by dannySOLO** [comment]
![Screenshot from 2020-01-11 00-25-52](https://user-images.githubusercontent.com/28641821/72172912-f7ccd380-3408-11ea-982e-22ae82ed30cb.png)
This is when I run 'howdy test'.

**Comment by dannySOLO** [comment]
![Screenshot from 2020-01-11 09-10-17](https://user-images.githubusercontent.com/28641821/72197291-3935a100-3452-11ea-9930-5f6d549fc7dc.png)

**Comment by boltgolt** [comment]
Sorry this issue must have slipped through my email at the time
