### ISSUE TITLE
Lock screen does not supported

### ISSUE THREAD

**Issue by pavelkq** [boltgolt/howdy#298]
When I try to unlock cinnamon-screensaver, HOWDY does not work. I can press "change user" and start with lightdm with face identity, but it's long way.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution: 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2

Howdy version: 2.5.1

**Comment by boltgolt** [comment]
Please use the search function. Take a look at [this](https://github.com/boltgolt/howdy/issues/28#issuecomment-396231042) comment
