### ISSUE TITLE
Video tutorial in README

### ISSUE THREAD

**Issue by Naveen3Singh** [boltgolt/howdy#309]
I made a video tutorial on Ubuntu here: https://youtu.be/bZvHaEiP81Y
It can be added to README. I can make one for Arch too but I guess Arch users don't need video tutorials :)

**Comment by corndog2000** [comment]
I would love a video tutorial for Arch.

**Comment by Doomsdayrs** [comment]
This can be done with a PR request

**Comment by boltgolt** [comment]
Sorry i didn't see this at the time, much of this is going to be outdated with the release of 3.0.0 and its GUI setup. Unfortunately i can't add this to the new readme, sucks that i only saw this while cleaning up old issues
