### ISSUE TITLE
Don't work on python3.8rc, using Ubuntu 20.04

### ISSUE THREAD

**Issue by ksusonic** [boltgolt/howdy#313]

**Comment by boltgolt** [comment]
Okay, what's the error

**Comment by ksusonic** [comment]
Sorry, I reinstalled the system and now it works well with same python version but on Kubuntu. By the way there's one more problem: on the lock screen after password input howdy starts to recognize your face and after that, it stuck on "password checking". There's a conflict with SDDM, but I think you know. I turned off the message after recognition in howdy config and it's ok now.
