### ISSUE TITLE
Howdy test - no labes or icons on buttons

### ISSUE THREAD

**Issue by exander77** [boltgolt/howdy#314]
I have Ubuntu 20.04. When I run the howdy test, there are no labels or icons on buttons in the menu.

**Comment by boltgolt** [comment]
I'm not sure what you're talking about, what menu?

**Comment by exander77** [comment]
Above camera windows, there is a menu with buttons for zooming etc. But buttons have no labels and/or icons. I completely missed them at the beginning. It shows just like a grey bar.

**Comment by boltgolt** [comment]
Ah yes, those are build-in buttons from opencv, they really should have labels but there's not much i can do about that unfortunately. Thanks for opening an issue anyway
