### ISSUE TITLE
Gstreamer warnings

### ISSUE THREAD

**Issue by ajnart** [boltgolt/howdy#318]
_Please describe the issue in as much detail as possible, including any errors and traces_

While attempting to use howdy, it gives me these warnings:
```
[ WARN:0] global /build/opencv/src/opencv-4.2.0/modules/videoio/src/cap_gstreamer.cpp (1758) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0] global /build/opencv/src/opencv-4.2.0/modules/videoio/src/cap_gstreamer.cpp (888) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /build/opencv/src/opencv-4.2.0/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```

----

Linux distribution (if applicable): Arch Linux 86_64

Howdy version: 2.5.1-2

**Comment by meeas** [comment]
Thank you!  After a recent update on Debian Testing, I started experiencing this same issue.  Confirming your patch fixed it for me.

**Comment by Cottand** [comment]
Can confirm the same

**Comment by principis** [comment]
This has to be changed again for 2.6.0
see https://github.com/boltgolt/howdy/blob/master/src/recorders/video_capture.py#L116

**Comment by baelter** [comment]
Fix got rid of the WARNs, but INFO logs can still create issues for GUI applications, eg. 1Password.
Tried setting `OPENCV_LOG_LEVEL=ERROR` in `/etc/environment` but still get info logs that causes an infinite loop of retries.'

Seeing this (repeated until the app is killed) in the logs:
```
Jun 10 13:36:13 fedora polkit-agent-helper-1[3851]: [HOWDY] Attempting facial authentication for user anders
Jun 10 13:36:14 fedora gnome-shell[1963]: Unknown line '[ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/videoio_registry.cpp >
```

**Comment by petre2dor** [comment]
@baelter  were you able to fix this? 
I would like to enable face recognition for polkit on fedora 34 with gnome and this issue is a blocker.

**Comment by baelter** [comment]
@petre2dor Nope 😔

**Comment by citizenserious** [comment]
I am seeing the same error on fedora 40 today. Howdy is working, but it takes a lot of time for it to start.

**Comment by ysz0507** [comment]
A small pointer from my side: I got the same warning on manjaro. I could resolve the problem by applying this commit from the current beta branch: https://github.com/boltgolt/howdy/commit/b04ffe5bd83683949db53bcaf2b91559e30d8e4c

**Comment by Nikusb9** [comment]
I resolved the issue with adding
`OPENCV_LOG_LEVEL=OFF`
to my user environment and adding this line to the top with visudo
`Defaults        env_keep += "OPENCV_LOG_LEVEL"`
