### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by bendandersen** [boltgolt/howdy#32]
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 98, in <module>
    import cli.test
  File "/lib/security/howdy/cli/test.py", line 5, in <module>
    import cv2
ImportError: No module named 'cv2'

**Comment by Boltgolt** [comment]
Could you try the solution in the last part of [this](https://github.com/Boltgolt/howdy/issues/7#issuecomment-368305023) comment?

**Comment by bendandersen** [comment]
The conda command is not found. Did I install something wrong?

**Comment by Boltgolt** [comment]
Could you try `sudo apt install libopencv-dev python-opencv`?

**Comment by bendandersen** [comment]
When I run that line in the terminal it returns with already having the
newest version. So I don’t think that’s it.

**Comment by Boltgolt** [comment]
Looks like you're only missing the python 3 bindings, could you try following 2, 2.1 and 2.2 of [this](https://milq.github.io/install-opencv-ubuntu-debian/) tutorial?

**Comment by stellarpower** [comment]
That worked for me.

**Comment by missxa** [comment]
was missing python3 bindings as well, fixed with `pip3 install opencv-python`

**Comment by janecz-n** [comment]
https://github.com/boltgolt/howdy/issues/32#issuecomment-386876427 work for me

**Comment by davidgaya** [comment]
```pip3 install opencv-python``` worked for me

**Comment by boltgolt** [comment]
It also works as expected on the travis 16.04 instance, it seems very machine dependent

**Comment by boltgolt** [comment]
python-opencv fails to install on many 16.04 installations though, which breaks this package all together if it would be a dependency. I might add a catch for a missing OpenCV library with a link to a wiki page with further instructions.

**Comment by boltgolt** [comment]
This last release should now automatically detect this problem and fix it. Feel free to reopen this issue if you still have the same problem on version 2.4.0 or above.

**Comment by VanVan** [comment]
Thank you, it works now.
However I needed to install these package, it was not automatic
```
sudo pip3 install opencv-python
sudo apt install libopencv-dev python-opencv
sudo pip3 install dlib
```
