### ISSUE TITLE
Howdy for user accounts

### ISSUE THREAD

**Issue by Doomsdayrs** [boltgolt/howdy#320]
I am not sure if this is already implemented or not, But is there a way to have howdy only let certain face login, but not use sudo. 

IE on Ubuntu:
- Administrator; All howdy features
- Standard; Only logging into their account

**Comment by Doomsdayrs** [comment]
Learned this via trial and error. It is a thing, and works

**Comment by boltgolt** [comment]
Did you use custom PAM rules?

**Comment by Doomsdayrs** [comment]
Nah, Just login to the user's account. and do `sudo howdy add`
