### ISSUE TITLE
Multiple cameras in order

### ISSUE THREAD

**Issue by paulelms** [boltgolt/howdy#322]
I have a built-in camera in my laptop, but sometimes I connect an external monitor and an external webcam. It would be convenient if howdy went through several cameras in order: if there is no first device (external camera), then use the built-in one.

**Comment by paulelms** [comment]
I meant the list in the device_path option

**Comment by boltgolt** [comment]
Checkout #515

**Comment by boltgolt** [comment]
Checkout #515
