### ISSUE TITLE
Does Howdy *need* IR sensors?

### ISSUE THREAD

**Issue by adrfantini** [boltgolt/howdy#327]
Hi and thanks for this project, it looks very interesting and cool!
I'd like to try it out, but I do not have a Windows Hello laptop - so no IR sensors. Are they really needed, or are they just added security?

The project description says `Use your built-in IR emitters and camera in combination with facial recognition to prove who you are.`, does this mean that IR sensors are necessary for this to work reliably?

**Comment by Doomsdayrs** [comment]
Not at all, I have it installed on laptops without IR sensors. 
It seems the models will just be more based on image then mapping of depth and such. 

TLDR; No, But you will be less secure, and some issues with recognition

**Comment by boltgolt** [comment]
Yes, there is not depth mapping as there really isn't a way to generate depth data. So a normal camera will do fine, but it's a LOT more easier to fool with a picture of you for instance

**Comment by adrfantini** [comment]
Got it, thanks! Maybe could be a bit more clear in the README

**Comment by boltgolt** [comment]
Don't want to encourage people to use Howdy with normal webcams though, not very secure

**Comment by adrfantini** [comment]
True, even though in some environments could be OKish (e.g. house computer with kids around).
Anyway a big disclaimer would be enough imho.
