### ISSUE TITLE
Incorrect error message on `howdy list` with no profiles

### ISSUE THREAD

**Issue by NuclearDog** [boltgolt/howdy#334]
When running `howdy list` with no profile set up, it reports:

```
$ sudo howdy list
Face models have not been initialized yet, please run:

	howdy myusername add
```

This doesn't appear to actually be valid `howdy` syntax, and should instead be:

```
$ sudo howdy list
Face models have not been initialized yet, please run:

	howdy -U myusername add
```

This error message can be generated at least two places:

https://github.com/boltgolt/howdy/blob/68f431e4bdd114fc4c165dc7de1b051011609e7f/src/cli/list.py#L17
https://github.com/boltgolt/howdy/blob/68f431e4bdd114fc4c165dc7de1b051011609e7f/src/cli/list.py#L28

**Comment by boltgolt** [comment]
Well spotted! Need to fix in next release
