### ISSUE TITLE
Camera path is not configured correcty - Fedora 31

### ISSUE THREAD

**Issue by RichBuck89** [boltgolt/howdy#339]
Hello, 

Using Fedora 31 trying to add the camera into the config. I don't understand what the camera path should be. I tried putting in /dev/video0, which works with v4l2ucp /dev/video0. 
I can also open the camera using cheese and it seems to display fine but I don't know how to get the camera path.

----

Howdy version:

**Comment by boltgolt** [comment]
Yes, `/dev/videoX` should all work. Try running `ls /dev | grep video` to see what video devices you have
