### ISSUE TITLE
Installation dependency error - Ubuntu 20.04

### ISSUE THREAD

**Issue by qiyoulu** [boltgolt/howdy#347]
Both the official Ubuntu version and the Debian version (2.5.1) had this dependency error during installation:

`dependency problems prevent configuration of howdy:
 howdy depends on libopencv-dev; however:
  Package libopencv-dev is not installed.`

Thank you!

**Comment by qiyoulu** [comment]
I solved the issue by downgrading liblzma5 from version 5.2.4-1ubuntu1 to 5.2.4-1.
This allowed the proper version of libopencv packages to be installed.

**Comment by gerrnot** [comment]
had a similar issue, solved it by running `sudo aptitude install howdy`. Had to reject the first proposed solution, then it suggested to downgrade only two dependencies.
