### ISSUE TITLE
test.py: error getting force_mjpeg

### ISSUE THREAD

**Issue by arifeinberg** [Boltgolt/howdy#35]
test.py:
 24 if config.get("debug", "force_mjpeg") == "true":

"debug" needs to be "video." :(  

Currently  test throws exception.

**Comment by Boltgolt** [comment]
Oops, I'll push a new version tomorrow

**Comment by arifeinberg** [comment]
Also add.py, but I think that's it.

**Comment by Boltgolt** [comment]
Fixed both, thanks for reporting!
