### ISSUE TITLE
Lock screen unlock doesnt work on Ubuntu

### ISSUE THREAD

**Issue by Fhesseti** [boltgolt/howdy#351]
It works fine for everything else, but times out on the lock screen. Tried  sudo chmod -R 755 /lib/security/howdy and setting the no_confirmation to true in the config.
[auth.log](https://github.com/boltgolt/howdy/files/4631514/auth.log)

**Comment by IAMGREATER** [comment]
Hi, I'm no expert but followed some other suggestions and added this line:

auth sufficient pam_python.so /lib/security/howdy/pam.py

To this file on line 2:

/etc/pam.d/sddm

All seems to be working now :)

**Comment by boltgolt** [comment]
Have you tried that solution @Fhesseti ?
