### ISSUE TITLE
IR Camera Flashes But Can't Add Face on Ubuntu 16.04.6

### ISSUE THREAD

**Issue by StormFalcon32** [boltgolt/howdy#358]
Howdy 2.5.1
During install, the IR camera flashes on the necessary step. Additionally, using cheese to check the webcam shows that it is working as well. However, adding a face gives me

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 89, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 147, in <module>
    gsframe = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Doing dmesg | grep "Unknown video format" gives
[    4.614702] uvcvideo: Unknown video format 00000032-0002-0010-8000-00aa00389b71

**Comment by boltgolt** [comment]
See [this comment](00000032-0002-0010-8000-00aa00389b71) for more info
