### ISSUE TITLE
Different camera used for IR and camera

### ISSUE THREAD

**Issue by galook** [boltgolt/howdy#362]
Hello,
I was installing Howdy on Ubuntu 20.04 via apt, and it asked me if the IR blasters are running during the installation. I have gone through the four options (devices), the first two didn't do anything, the third one fired up the IR blasters and the camera led was turned off, the fourth (last) one only fired up the camera led, not the IR.

What can I do to use both the camera and the IR blasters, how I suppose face recognition is intended to work?

**Comment by boltgolt** [comment]
What does running `ls /dev/v4l/by-path` return?

**Comment by galook** [comment]
It does return this:
```
pci-0000:00:14.0-usb-0:5:1.0-video-index0
pci-0000:00:14.0-usb-0:5:1.0-video-index1
pci-0000:00:14.0-usb-0:5:1.2-video-index0
pci-0000:00:14.0-usb-0:5:1.2-video-index1
```
The ones ending -index0 don't do anything on installation, the first one ending -index1 are the IR blasters, the second one is the camera.

**Comment by thecreativeone91** [comment]
I have the same issue on Ubuntu 20.04 with my lenovo Carbon X1. I can get it working using the webcam only but it does not use IR. Funny thing is Zoom Meetings shows both cameras and the IR one turns on the IR lights and has a B&W image. I can use Howdy using my normal webcam but not the IR one it won't detect a face on those. 

This is what mine returns

```
pci-0000:00:14.0-usb-0:5:1.0-video-index0
pci-0000:00:14.0-usb-0:5:1.0-video-index1
pci-0000:00:14.0-usb-0:8:1.0-video-index0
pci-0000:00:14.0-usb-0:8:1.0-video-index1
```

**Comment by boltgolt** [comment]
Could be a `dark_threshold` issue, try upping that to 100 in the config
