### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by LeoSavard** [boltgolt/howdy#363]
Hi,
I've been using Howdy with my old macbook pro on pop_os since it works even with a non-ir camera. However I've switched my laptop to clear Linux to benefit from the better optimizations regarding speed and overall responsiveness on my 8 year old system. Is it possible to build Howdy from source or do you require that packages be distro-specific?

**Comment by boltgolt** [comment]
Well, Howdy is written in python 3, so it should really run anywhere. There's no real build process and you basically only have to configure Howdy and point PAM in the right direction. The [openSUSE wiki](https://twitter.com/NicolasEstrup/status/1268570956672520198) has a good explanation of what you have to do

**Comment by qiyoulu** [comment]
that's not the opensuse wiki

**Comment by boltgolt** [comment]
Mispaste sorry!

**Comment by LeoSavard** [comment]
> Well, Howdy is written in python 3, so it should really run anywhere. There's no real build process and you basically only have to configure Howdy and point PAM in the right direction. The [openSUSE wiki](https://en.opensuse.org/SDB:Facial_authentication) has a good explanation of what you have to do

Thank you! It's basically plug and play!
