### ISSUE TITLE
Use howdy to unlock 1Password

### ISSUE THREAD

**Issue by Naragorn** [boltgolt/howdy#364]
How cool would it be to use howdy to unlock third party apps like 1Password!

1Password has this feature for Apple and Windows however not for Linux.

**Comment by boltgolt** [comment]
While this would be really cool, i think it's outside the scope of Howdy. It's up to 1Password to fix this

**Comment by FIUSHerson** [comment]
> How cool would it be to use howdy to unlock third party apps like 1Password!

I haven't tested it yet, but 1Password should be able to use Howdy if you enable System Authentication in 1Password.

**Comment by Naragorn** [comment]
You are correct! This works, I just tested it.

To do this enable System Authentication like so:
https://support.1password.com/system-authentication-linux/

Then add this line
`auth sufficient pam_python.so /lib/security/howdy/pam.py`

to your 
`etc/pam.d/system-auth`

**Comment by boltgolt** [comment]
That's really cool to hear!
