### ISSUE TITLE
Default to /dev/v4l/by-id instead of by-path?

### ISSUE THREAD

**Issue by ryanerwin** [boltgolt/howdy#368]
Howdy,

I'm running Ubuntu 20.04 with a Logitech Brio and I'm amazed at how many components were required for the howdy install, but it all went properly and worked basically out of the box.

Unfortunately, I've got so many USB devices plugged in the "by-path" seems to be a bit random for devices... So after reboot, Howdy stopped working. The install itself was so smooth, it wasn't obvious what to do next.

Ultimately just had to run `howdy config` and set the `device_path` to use `/dev/v4l/by-id` and everything seems fine. For people using Howdy, I just suggest that `by-id` might be a better default than by-path unless `by-id` has some downside...

Thanks for your time.

**Comment by boltgolt** [comment]
Good suggestion, thanks! Unfortunately if you have more than one video input in one USB device (such as all Windows Hello laptops) it will only be reported as 1 input in `/by-id`, while it's split correctly into the IR and visible light camera in `/by-path`.

Having said that, this will be very useful for people using an external camera, so i hope they can find this thread
