### ISSUE TITLE
On facial recognition fail, ask for password

### ISSUE THREAD

**Issue by ralphocdol** [boltgolt/howdy#372]
This was on version **2.5.1**, though I believe it was not a feature but rather a behavior.

It would be nice to have it as an option when if it `fails` or the `user deliberately prevents, stops or skip` the facial recognition then ask for a sudo password instead rather than waiting for the timeout or the number of times it will ask.

This is good specially at night where your cheap camera can't see your face.

Hoping to see this on next updates.

I'm on version **2.6.0**

**Comment by boltgolt** [comment]
It still does exactly what you're describing unless you have a non-default PAM setup

**Comment by ralphocdol** [comment]
I believe I did not touch anything except `no_confirmation` in the config. It was working before I update to 2.6.0

**Comment by GarvTambi** [comment]
Sometimes face detect successfully and sometimes it shows Unknown Error:1 Why?
Please help!

![dfg](https://user-images.githubusercontent.com/42083679/87365666-6f381700-c594-11ea-820e-2ca6e7c5dff9.jpeg)
