### ISSUE TITLE
Howdy to unlock SSH key?

### ISSUE THREAD

**Issue by ryanerwin** [boltgolt/howdy#377]
Any thoughts on how to connect Howdy an ssh-agent or otherwise use Howdy to unlock SSH keys?

Would be preferable to sit in front of my monitor to decrypt my SSH keys rather than repeatedly typing in a password...

A bit more fun than keeping everything in the keychain.

How difficult to connect Howdy to other apps or embed Howdy in other apps?

**Comment by GarvTambi** [comment]
Sometimes face detect successfully and sometimes it shows Unknown Error:1 Why?
Please help!

![dfg](https://user-images.githubusercontent.com/42083679/87365286-7a3e7780-c593-11ea-8442-2ba7a46c1354.jpeg)

**Comment by boltgolt** [comment]
I believe your SSH keys are encrypted with your password, so you will always have to enter your password to decrypt them. There's no way Howdy can be of use here unfortunately

**Comment by nixigaj** [comment]
If you use disk encryption and use a SSH key password as a way to protect it from rouge applications running as your user or some person having physical access to your device when logged in, you can store your `.ssh` folder in another users home directory, that you then use sudo to get to. I created a user `sshuser` and moved my unencrypted `.ssh` folder there, and then i have the alias `alias ssh-example="sudo -u sshuser ssh user@example.com"`. Then you can use Howdy auth through sudo.
