### ISSUE TITLE
warning while running

### ISSUE THREAD

**Issue by GlazedPineapple** [boltgolt/howdy#382]
_Please describe the issue in as much detail as possible, including any errors and traces_
When I run somthing that calls howdy I get this warning:
[ WARN:0] global /build/opencv/src/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (1758) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0] global /build/opencv/src/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (888) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /build/opencv/src/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):
Manjaro
Howdy version:
2.6.0

**Comment by CybernetiX-S3C** [comment]
I get the same thing. 

```
sudo howdy test                 
[ WARN:0] global /home/cybernetix-s3c/OpenCV/modules/videoio/src/cap_gstreamer.cpp (1758) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0] global /home/cybernetix-s3c/OpenCV/modules/videoio/src/cap_gstreamer.cpp (888) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /home/cybernetix-s3c/OpenCV/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```
```
uname -a                                                                                                    100 ⨯
Linux CybernetiX-S3C 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1 (2020-12-18) x86_64 GNU/Linux
```
