### ISSUE TITLE
Version 2.6.0 "Broadcast message from systemd-journald" problem on Manjaro

### ISSUE THREAD

**Issue by bobzhu418** [boltgolt/howdy#385]
After upgrading to version 2.6.0, every time if I use sudo on terminal, I get following message. It's not fatal but very irritating. 

```
Broadcast message from systemd-journald@manjaro (Sat 2020-07-04 10:08:23 +08):

sudo[2580]: [HOWDY] Attempting facial authentication for user bob


Broadcast message from systemd-journald@manjaro (Sat 2020-07-04 10:08:25 +08):

sudo[2580]: [HOWDY] Login approved
```

Linux distribution (if applicable): Manjaro 20.0.3 Kernel 5.7.0-3

Howdy version: 2.6.0

**Comment by bobzhu418** [comment]
Ok, I found a work-around. Set `ForwardToWall=no` in `/etc/systemd/journald.conf` to disable the broadcasting.

**Comment by GarvTambi** [comment]
Sometimes face detect successfully and sometimes it shows Unknown Error:1 Why?
Please help!

![dfg](https://user-images.githubusercontent.com/42083679/87365253-609d3000-c593-11ea-9e8f-707f7e887fec.jpeg)

**Comment by boltgolt** [comment]
Thanks for reporting! To keep discussion about it in one place i'm going to close this now, see #374
