### ISSUE TITLE
Your keyring did not get unlocked at the time you logged in to your computer

### ISSUE THREAD

**Issue by akabhirav** [Boltgolt/howdy#39]
I am receiving a dialog saying that and asking for a password. Is it possible to log into the keyring as well as the user account?

If it is can you make that change

**Comment by wzrdtales** [comment]
I would say this is rather not an issue but expected. The keyring by default gets **decrypted** with your password. Which is the only way their storage can be guaranteed to be secure. However once you're logged in the keyring keeps decrypted, so I would consider facial recognition rather a quick way to login you again rather than being the main way to log you in. Which is terribly insecure anyway.

**Comment by Boltgolt** [comment]
This module is explicitly not made to be more secure than a password, just faster. It's a trade off you have to make.

If you want to you can disable the password for your keyring so it will get unlocked automatically. To do this open "Passwords & keys" from the dash, right click the "Login" keyring and change the password to an empty one.

Please be aware that this is insecure and will make the passwords in that keyring easier to crack. It's about the same level of security as saving passwords in chrome/firefox without a master password.

**Comment by robquinn** [comment]
I don't mean to be mean or negative, but if you have to enter a password, what's even the point of facial recognition? It just adds an unnecessary step if you have to enter your password anyway. Seriously, I'm not trying to be an a-hole, I am open to any feedback that would help me understand this better or whatever.

**Comment by boltgolt** [comment]
You make valid points, and i would not recommend Howdy on login if you have to unlock your keychain with a password after that anyway. 

There are 2 major use cases here: One group of users users doesn't have a keychain to unlock. For example: If you don't use Chrome on Ubuntu 16.04 and don't have an encrypted home dir then chances are you don't have a keychain active. Another set of users that do have to enter a password only use Howdy for specific authentication types, like sudo and gnome-screensaver, that come after the login screen and thus never require a password.

**Comment by robquinn** [comment]
@boltgolt I really appreciate the feedback. I get that what I said could be hurtful and taken the wrong way. I'm glad you're level headed and didn't take it that way. You're obviously a cool dude lol. Thanks again :smile:

**Comment by boltgolt** [comment]
No problem! I don' find it hurtful at all, constructive criticism should always be allowed. [This wiki article](https://github.com/boltgolt/howdy/wiki/Only-using-howdy-for-specific-authentication-types) might be useful to you btw

**Comment by chocomo99** [comment]
Running Ubuntu 20.04.X LTS. A recent update appears to have installed Skype. I know that's weird. Skype auto-opened after login then prompts me to create an account. Finally I did and then realized I had those services free from other providers. Afterward on login I would get "keyring did not get unlocked" popup. Problem went away after uninstalling Skype. Seems weird but there it is...  Once again glad to be off the Microsoft merry-go-round.

**Comment by expl0r3rgu1** [comment]
> Running Ubuntu 20.04.X LTS. A recent update appears to have installed Skype. I know that's weird. Skype auto-opened after login then prompts me to create an account. Finally I did and then realized I had those services free from other providers. Afterward on login I would get "keyring did not get unlocked" popup. Problem went away after uninstalling Skype. Seems weird but there it is... Once again glad to be off the Microsoft merry-go-round.

The popup is likely to be gone because Skype was probably the only app on your system that after logging in was waiting for the login keyring to get unlocked.

**Comment by boltgolt** [comment]
That's not possible, but you could set your keyring password to an empty string. This completely disables your keyring encryption and is not recommended

**Comment by joezhouchenye** [comment]
Empty string temporarily works. After some time when I rebooted the laptop, the keyring password was reset to the user's password on Ubuntu 23.04 for some unknown reason.
