### ISSUE TITLE
Unknown Error:1

### ISSUE THREAD

**Issue by GarvTambi** [boltgolt/howdy#392]
Sometimes face detect successfully and sometimes it shows Unknown Error:1 Why?
Please help!

![dfg](https://user-images.githubusercontent.com/42083679/87366198-bd99e580-c595-11ea-8ff8-212721dad118.jpeg)

**Comment by boltgolt** [comment]
You've been blocked from  participating, posting the same thing 10+ times is not how you should behave and you know that. You've had plenty of warnings.
