### ISSUE TITLE
Improve face recognition?

### ISSUE THREAD

**Issue by reylinux** [boltgolt/howdy#399]
Hello again,

How do we train the accuracy of howdy? I got 8 models with different angle & distance, yet it is still hard to make it works.

Is there any tips for this?

Thank you

$ sudo howdy list
Face detection timeout reached
[sudo] password for reynaldi:         
Known face models for reynaldi:

	ID  Date                 Label
	0   2020-07-18 17:42:49  1
	1   2020-07-18 17:43:01  2
	2   2020-07-18 17:43:16  3
	3   2020-07-18 17:43:24  4
	4   2020-07-18 17:43:30  5
	5   2020-07-18 17:43:39  6
	6   2020-07-18 17:43:50  7
	7   2020-07-18 17:43:58  8

Linux distribution (if applicable):
Elementary OS

Howdy version:
Latest version

**Comment by boltgolt** [comment]
I'd advice you to not have _too_ many models, it slows recognition down. Try making 3 or 4 models in different lighting environments. It might also help to turn on the `capture_failed` config option and look at the images in `/lib/security/howdy/snapshots/` that it generates
