### ISSUE TITLE
Missing dependency python3-dlib on Fedora

### ISSUE THREAD

**Issue by cnyk** [boltgolt/howdy#403]
Using copr repo luya/howdy (from readme), installed howdy and on first run I got 
$ sudo howdy add
No module named 'dlib'

Can't import the dlib module, check the output of
pip3 show dlib

Issue is fixed by installing python3-dlib.

Please add dependecy python3-dlib in spec file

**Comment by cnyk** [comment]
Patch link https://github.com/cnyk/howdy/commit/fad52c556bed187ac9a1f26d425aa0a39568d5e8

**Comment by boltgolt** [comment]
Could you also open a PR for that one?

**Comment by boltgolt** [comment]
Fixed in 2.6.1, just waiting for fedora release
