### ISSUE TITLE
Is it possible to just use howdy for sudo

### ISSUE THREAD

**Issue by nick-stocks** [boltgolt/howdy#410]
I'd like to keep using a password for logging in, and only use howdy for `sudo`. Is this possible? I can't see an obvious setting in config

**Comment by boltgolt** [comment]
Yes, take a look at [this wiki page](https://github.com/boltgolt/howdy/wiki/Only-using-howdy-for-specific-authentication-types)

**Comment by nick-stocks** [comment]
Awesome thankyou!!
