### ISSUE TITLE
Option to skip Howdy if another monitor is attached

### ISSUE THREAD

**Issue by alexanderadam** [boltgolt/howdy#411]
I guess the title says it all.
I'm not looking to the IR & camera on the notebook when I have an external monitor attached.

It is related to #345 but is dedicated to another functionality obviously.

**Comment by boltgolt** [comment]
While this would be a good addition, it would add an additional dependency that i'm not sure a lot of people use. Maybe it's possible to make a bash script that takes input from the `xrandr` and feeds it into `sudo howdy disable`?

**Comment by mikk150** [comment]
you should be able to read this information from `/sys/class/drm`, it should work with wayland and X11

**Comment by alexanderadam** [comment]
Okay, but I'm still not sure what to do now.
So how/where exactly should I use that information? I'm not even sure how howdy is integration in which parts of the system. :shrug:
