### ISSUE TITLE
Howdy adds face models but does not ever detect a face: BadDrawable (invalid Pixmap or Window parameter) 9

### ISSUE THREAD

**Issue by Seltonu** [boltgolt/howdy#416]
_Please describe the issue in as much detail as possible, including any errors and traces_

I can add face models to Howdy, but any command with sudo never detects a face, not even "sudo howdy test". I have edited the config file to change the device path to /dev/video2 and my IR camera does fire, but no dice. This is the output of "sudo howdy test":

![image](https://user-images.githubusercontent.com/10287568/89743441-bd0c4600-da92-11ea-925a-c6f868912263.png)

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Pop!_OS 20.04 (Ubuntu variant) with Linux kernel 5.8 (didn't work on 5.7 or 5.6 either). 

Howdy version: 2.6.0

**Comment by boltgolt** [comment]
Actually use the search function next time, see #128
