### ISSUE TITLE
IR emitters don't stay on

### ISSUE THREAD

**Issue by Hashfastr** [Boltgolt/howdy#42]
Hello, I am running Ubuntu 18.04 and I've noticed that the IR emitters built into my IR camera only flashes on for a second when howdy starts then subsequently turns back off. During installation however it strobed when choosing which camera was the IR camera. This makes all frames dark frames and my only hope for face authentication is sitting in the sunlight for a natural source of IR light. This also persists if I use Cheese using the IR camera.

**Comment by Boltgolt** [comment]
Unfortunately this is a known problem with some cameras. For some reason the emitters only blink when skipping frames which is useless. Take a look at #19 for a little more information
