### ISSUE TITLE
XPS 15 9500 with Xubuntu 20.04 LTS

### ISSUE THREAD

**Issue by betterwithchem** [boltgolt/howdy#423]
Hello, 

I've installed Howdy on my XPS 15 9500 with Xubuntu 20.04 LTS, during the installation howdy couldn't configure the camera automatically so after the installation I modified the config file changing the value of `device_path` from `/dev/v4l/by-path/none` to `/dev/video2` as the command `ffmpeg -f v4l2 -list_formats all -i /dev/video2` returns `[video4linux2,v4l2 @ 0x55a95a4eb6c0] Raw       :        gray :      8-bit Greyscale : 576x360`

However, if I run `sudo howdy test` I get:
`Camera path is not configured correctly, please edit the 'device_path' config value.`
`Exception ignored in: <function VideoCapture.__del__ at 0x7efbf36654c0>
Traceback (most recent call last):`
`  File "/usr/lib/security/howdy/recorders/video_capture.py", line 55, in __del__
    self.internal.release()`
`AttributeError: 'VideoCapture' object has no attribute 'internal'`

How can I fix this?
Thank you

**Comment by ajzat34** [comment]
I'm using a 9500 on pop_os and /dev/video0 worked for me

**Comment by Danhyal-Masood** [comment]
did you modify the recording plugin? make sure you have opencv installed and set the recording_plugin variable to opencv. This works for me although on arch.

**Comment by betterwithchem** [comment]
> did you modify the recording plugin? make sure you have opencv installed and set the recording_plugin variable to opencv. This works for me although on arch.

No, I didn't modify that line and the variable is already set to opencv. 
I checked and opencv is already installed:
`sudo pip3 install opencv-python` 
returned 
`Requirement already satisfied: opencv-python in /usr/local/lib/python3.8/dist-packages (4.3.0.36)`
`Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from opencv-python) (1.19.1)`

**Comment by betterwithchem** [comment]
Quick update:

the "Camera path" error and the "VideoCapture" exception error were due to me leaving a comment after the device_path variable on the same line (i.e `device_path = /dev/video2  #/dev/v4l/by-path/none')

Now I have a problem with the screen unlocking (showing "Unknown error: 1", as reported in another issue here on github.
I'll close this issue as this specific problem is solved.
