### ISSUE TITLE
Add/change log output config

### ISSUE THREAD

**Issue by aswen** [boltgolt/howdy#426]
Since I upgraded howdy from `2.6.0` (on my Debian Stretch laptop) I got broadcast messages like these:
```
Broadcast message from systemd-journald@thing (Mon 2020-08-31 09:45:44 CEST):

sudo[21314]: [HOWDY] Attempting facial authentication for user alex


Broadcast message from systemd-journald@thing (Mon 2020-08-31 09:45:49 CEST):

sudo[21314]: [HOWDY] Failure, timeout reached
```

I like logging but this was a bit too much. After failing to find a config option in Howdy to tune logoutput I changed two things:
1. I created `/etc/rsyslog.d/howdy.conf`:
  ```
  :msg,regex,"[HOWDY]" -/var/log/auth.log
  # Do not log these messages any further.
  :msg,regex,"[HOWDY]" ~
  ```

2. I told systemd-journald to stop shouting to wall by setting `ForwardToWall=no` in `/etc/systemd/journald.conf` and restart it: `resystemctl restart systemd-journald`.
  This isn't a problem of Howdy, but still, it helps to avoid useless broadcasts.

I hope this helps in improving Howdy even more.

**Comment by boltgolt** [comment]
This has been fixed by [this PR](https://github.com/boltgolt/howdy/pull/406/files#diff-0f559fb5dbc1ab411bff3c7f0145b9c2), but i haven't had the time to release it yet, sorry
