### ISSUE TITLE
Use howdy without IR

### ISSUE THREAD

**Issue by devmrfitz** [boltgolt/howdy#428]
Is it possible to use howdy with a normal webcam (without IR support)? I understand that IR is essential in insufficient light, but if  the lighting is bright enough, can I use Howdy on a normal webcam?

**Comment by mzzntn** [comment]
Yes you can it works perfectly even without IR but, as you can imagine the level of security will be lower

**Comment by amirkaveh** [comment]
You can use it either with or without an IR camera. Set your desired camera in the config file using `sudo howdy config` and write a camera path in front of device_path.
You can find your camera paths using the "v4l-utils" package and with the `v4l2-ctl --list-devices` command.

**Comment by boltgolt** [comment]
You can but it's not a great solution. Just a picture of you on a phone will probably fool Howdy when using a normal webcam.

**Comment by devmrfitz** [comment]
> You can but it's not a great solution. Just a picture of you on a phone will probably fool Howdy when using a normal webcam.

Can an "eye blink detection" be integrated somehow?

**Comment by boltgolt** [comment]
Possibly, if you want you can open a new issue for that
