### ISSUE TITLE
Where does the beeping sound come from ? Can I make it quieter ?

### ISSUE THREAD

**Issue by ozls** [boltgolt/howdy#429]
Hi,

I am using Howdy and I love it. It works perfectly. This is not really an issue nor a feature request, but I am getting a beeping sound each time Howdy starts and authenticates me, so two times. Its useful I guess, but it's also very loud and I would like to tone it down / replace it with a notification or something. Where does that sound come from ? Does anybody else have this ?

I am using Manjaro with Linux kernel 5.7.15 and Howdy 2.6.0 from the AUR. Thanks in advance !

**Comment by ozls** [comment]
Closed because I used a trick to disable this speaker beeping altogether. But I'm still interested in how Howdy makes the speakers beep.

**Comment by boltgolt** [comment]
I'm thinking the beeping was caused by Howdy accidentally sending a emergency broadcast on every authentication prompt, this should be fixed in 2.6.1

**Comment by tarun-varier** [comment]
@ozls what trick did u use tho to disable that annoying sound?
xset b off doesn't make no differencce

**Comment by ozls** [comment]
The annoying, full volume beeps come from the `pcspkr` module (on my Manjaro install at least). I think what I did was `echo "blacklist pcspkr" | tee /etc/modprobe.d/nobeep.conf`. I found it [here](https://wiki.archlinux.org/index.php/PC_speaker)

**Comment by tarun-varier** [comment]
@ozls thanks a ton...you are a messiah
