### ISSUE TITLE
Exposure Varies Too Much between Light and Dark Images

### ISSUE THREAD

**Issue by dav-is** [boltgolt/howdy#435]
It seems like the brighter IR image is being overexposed. The darker image seems just about right.

![20200903T120830](https://user-images.githubusercontent.com/11590024/92121242-0d43a300-edc8-11ea-8290-b3cc6fbe143c.jpg)
![20200903T120852](https://user-images.githubusercontent.com/11590024/92121273-159bde00-edc8-11ea-8f3a-2e5c09e96c9a.jpg)
How is it possible one of these failed and the other was successful... they both look pretty close to me

Here, the brighter image looks about right, but the darker images are barely exposed.
![20200902T222217](https://user-images.githubusercontent.com/11590024/92121478-53006b80-edc8-11ea-8bc3-b4f1b0cb98d6.jpg)

Maybe we need a few moments of low exposure, then a few moments of high exposure (sort of like how HDR works)

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu 20.04

Camera: Logitech Brio

Howdy version (`sudo howdy version`): 
```
$ sudo apt list howdy
Listing... Done
howdy/focal,focal,now 2.6.1 all [installed]
```

**Comment by dav-is** [comment]
It looks fine when using `sudo howdy test` but it seems pretty unreliable and times out when recognizing outside of testing. The only way I've seen to debug is using these screenshots

**Comment by eskander12** [comment]
but can you not just make it so it takes a bit longer before the picture is saved

**Comment by boltgolt** [comment]
You're replying to a 2-year-old issue but in short it's normally good for diagnosing issues to save the first few frames
