### ISSUE TITLE
Division by Zero in History, compare.py

### ISSUE THREAD

**Issue by stellarpower** [boltgolt/howdy#44]
Hi,

I'm getting errors when trying to sudo, evidently the history is missing.

  File "/lib/security/howdy/compare.py", line 101, in <module>
    if float(hist[0]) / hist_total * 100 > float(config.get("video", "dark_threshold")):
ZeroDivisionError: float division by zero
Unknown error: 1

is the backtrace.

I'll try to take a look when I can.

Cheers

**Comment by boltgolt** [comment]
Found the issue: If every single pixel of the frame is exactly rgb(0,0,0), the sum of the histogram will be zero. I'll add a fix in the next patch but for now you can add

```python
	if hist_total == 0:
		dark_tries += 1
		continue
```

on line 100 in `/lib/security/howdy/compare.py`
