### ISSUE TITLE
" 'VideoCapture' object has no attribute 'internal' " after trying add a new face model

### ISSUE THREAD

**Issue by atahan2000** [boltgolt/howdy#441]
Got this exception error after trying to add a face.

"""
Exception ignored in: <function VideoCapture.__del__ at 0x7f338bb7ad30>
Traceback (most recent call last):
  File "/usr/lib/security/howdy/recorders/video_capture.py", line 55, in __del__
    self.internal.release()
AttributeError: 'VideoCapture' object has no attribute 'internal'
"""

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu

Howdy version (`sudo howdy version`): 2.6.1

**Comment by boltgolt** [comment]
Please search for other issues with you error before opening a new one

**Comment by epgeroy** [comment]
I have the same issue, any information related to this?

thanks in advance

**Comment by boltgolt** [comment]
See #533
