### ISSUE TITLE
GUI for Howdy (config especially) 

### ISSUE THREAD

**Issue by LorenDB** [boltgolt/howdy#449]
I am interested in creating a Qt-based GUI for configuration of Howdy for Hacktoberfest. Would this be approved?

**Comment by LorenDB** [comment]
> I am interested in creating a Qt-based GUI for configuration of Howdy for Hacktoberfest. Would this be approved? 

    I think that I will create an organization for hosting this project myself.

**Comment by boltgolt** [comment]
Hey! Sorry for not getting back to you sooner, i don't monitor closed issues very well. A GUI would be very much appreciated, especially if it's in something like GTK so it could be distributed as `howdy-gkt` for instance

**Comment by LorenDB** [comment]
OK, we'll see what I come up with. I don't know GTK, so it will need to be Qt.
________________________________

**Comment by mcgivrer** [comment]
Any news on this very interesting subject ?

**Comment by LorenDB** [comment]
Well. It turns out that I gave up on the idea since my laptop's camera isn't IR and therefore is very bad for facial recognition. Maybe someday if and when I get an IR camera....

**Comment by boltgolt** [comment]
@mcgivrer there's a working GUI on the beta branch, but it's waiting for other changes in the 3.0.0 version

**Comment by SaadBazaz** [comment]
Really would be great, so the UX is better when adding faces. It'd be great if it could have a shortcut in Settings.
