### ISSUE TITLE
Wont work with mask

### ISSUE THREAD

**Issue by orangemn6** [boltgolt/howdy#459]
_Please describe the issue in as much detail as possible, including any errors and traces._
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

When I try to add a face with my mask on it doesn't work

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):
Ubuntu
Howdy version (`sudo howdy version`):
2.6.1

**Comment by boltgolt** [comment]
This is intended behavior; your face isn't visible
