### ISSUE TITLE
Login keyring does not get unlocked when logging in with face recognition.

### ISSUE THREAD

**Issue by badmannen** [boltgolt/howdy#461]
_Please describe the issue in as much detail as possible, including any errors and traces._

- Program works flawless except that once I log in I still have to type the password for the "keyring", this does not become unlocked when logging in for some reason.
not a major issue, and for any other "sudo" commands it works perfect.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): POP!_OS 20.10

Howdy version (`sudo howdy version`): Howdy 2.6.1

**Comment by boltgolt** [comment]
Please search other issues before opening a new one, check out #438
