### ISSUE TITLE
Cannot be built on the latest Arch Linux

### ISSUE THREAD

**Issue by bobzhu418** [boltgolt/howdy#462]
Because Arch Linux has removed Python2 packages from its repository, the latest Howdy cannot be built any more. Below is the error message:

```
 -> Could not find all required packages:
    python2-sphinx (Wanted by: howdy -> pam-python)
    python2-sphinx (Wanted by: howdy)
```
----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Arch Linux (Kernel 5.9.2)

Howdy version (`sudo howdy version`): 2.6.1

**Comment by bageljrkhanofemus** [comment]
its because the pam-python package needs python2-sphinx to produce documentation. You can remove the documentation from the pkgbuild and the sphinx requirement from both pkgbuilds.

**Comment by bobzhu418** [comment]
Yes. You're right. I've built the the package successfully. Thanks!

**Comment by ginhiki** [comment]
> Yes. You're right. I've built the the package successfully. Thanks!

Facing the same issue, can you say how you rebuilt the package?
