### ISSUE TITLE
Take photo every time a user logs in

### ISSUE THREAD

**Issue by cleder** [boltgolt/howdy#468]
I had some problems with howdy not recognizing my face probably due to insufficient training data.

I came up with a simple script that takes a picture every time a user logs in.
You can run it for a couple of weeks before activating howdy to get a sample of images to train on
https://github.com/cleder/login-picture

**Comment by boltgolt** [comment]
Thanks! Did you turn on failed login attempt snapshots to see if you were recognized but did not meet the minimum configured certainty value?

Howdy normally does not need training, it uses a generally pretrained neural network
