### ISSUE TITLE
Disable howdy during specified time

### ISSUE THREAD

**Issue by arifer612** [boltgolt/howdy#469]
Before I begin, I'd like to thank you all for all the hard work. Howdy is my go-to authenticator after I lost the use of my fingerprint sensor (XPS 9380).

## Issue:
Regarding the topic at hand, I'd like to suggest a feature to implement in howdy. Having the option to disable howdy at night would solve 3 problems:

1. The need to wait for the PAM to return a `capture_failed` signal before typing in the password because the environment is too dark.

2. The need to manually disable it every time at night just to bypass Problem 1.

3. The overpopulation of dark `capture_failed` snapshots because of Problem 1.

## Suggestion:
Allow `disabled` in `config.ini` to specify the user's preferred time frame for howdy to be automatically disabled. 

### Effect on the program's runtime:
I changed my settings and the `pam.py` source code to test it out and observed no significant change in the runtime. If the idea is okay, may I submit a pull request for my changes?

Cheers!

**Comment by boltgolt** [comment]
Hey, thanks for the suggestion! While i see the use case of this, i'm going to mark this as wontfix for now. 

Howdy is primarily meant for IR cameras with build-in IR emitters that do not have a problem doing recognition in dark environments. Besides that i also believe that the same functionality can be achieved with a bash script and the `howdy disable` command. If enough people want this anyway then i'm definitely open for pull requests
