### ISSUE TITLE
Failfast if camera is in use

### ISSUE THREAD

**Issue by tdaniely** [boltgolt/howdy#475]
I commonly encounter a situation where I'm in a google meet session, I'm running `sudo something` in console, or getting some other polkit prompt.
In this situation howdy fails because the camera is locked, But the recognition timeout is applied so I have to wait the timeout until I can enter my password.

Can quick fix this by either failing fast if the camera is locked, or having a seperate timeout config for when device is in use.

**Comment by boltgolt** [comment]
That's weird, when the camera is busy it should throw an error that it can't open the device. Are google meet and Howdy using the same video device?

**Comment by tdaniely** [comment]
Actually no, I symlinked the device as I described in the multiple camera issue, I'll test it without the symlink and post back.

**Comment by Doomsdayrs** [comment]
@tdaniely Results?

**Comment by tdaniely** [comment]
Sorry I completely forgot about this.
It was due to a hack I did to switch to the dock camera when the laptop is docked.
