### ISSUE TITLE
PPA 404  Not Found Error

### ISSUE THREAD

**Issue by PJSingh5000** [boltgolt/howdy#485]
I get the following error while running `sudo apt update` on Ubuntu 20.10.
It looks like there are some files missing on the PPA?

```
Err:10 http://ppa.launchpad.net/boltgolt/howdy/ubuntu groovy/main DEP-11 48x48 Icons
  404  Not Found [IP: 91.189.95.85 80]
.
.
.
Reading package lists... Done
E: Failed to fetch http://ppa.launchpad.net/boltgolt/howdy/ubuntu/dists/groovy/main/dep11/icons-48x48.tar  404  Not Found [IP: 91.189.95.85 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Here is the contents of my sources list...
```
$ cd /etc/apt/sources.list.d
$ cat boltgolt-ubuntu-howdy-groovy.list 
deb http://ppa.launchpad.net/boltgolt/howdy/ubuntu/ groovy main
# deb-src http://ppa.launchpad.net/boltgolt/howdy/ubuntu/ groovy main
```

----

✓ I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu 20.10

Howdy version (`sudo howdy version`): Howdy 2.6.1

**Comment by boltgolt** [comment]
Seems like there are problems with the groovy release, maybe try apt update?
