### ISSUE TITLE
Whenever I boot up into 21.04, I get this error message: Sorry, the application has cli.py has stopped unexpectely.

### ISSUE THREAD

**Issue by goelvatsal** [boltgolt/howdy#496]
I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):
Ubuntu 21.04 Beta

Howdy version (`sudo howdy version`):
Howdy 2.6.1

Whenever I boot up into 21.04, I get this error message: Sorry, the application has cli.py has stopped unexpectely.

![Screenshot from 2021-01-13 22-49-50](https://user-images.githubusercontent.com/31752052/104542528-b067bd00-55f1-11eb-8036-d01b93115016.png)

**Comment by boltgolt** [comment]
Weird, seems like `howdy test` is executed on bootup, have your made that a startup application?

**Comment by goelvatsal** [comment]
No, I don't know how to set application to startup

**Comment by dswij** [comment]
Can you confirm if `python3 /usr/local/bin/howdy test` command is in the startup applications list? (in Ubuntu, i believe it's https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html.en)

**Comment by goelvatsal** [comment]
Hi dswij, I reinstalled Ubuntu a while back and it appears to be working now. Thanks for your help! I'm going to close this thread.
