### ISSUE TITLE
Test mode need some improvements.

### ISSUE THREAD

**Issue by leoheck** [boltgolt/howdy#499]
Using version 2.6.1

The test version is not really good, I cannot increase the window. It does not show the text in the bottom of the window.
![image](https://user-images.githubusercontent.com/1277920/104973965-29da2380-59d5-11eb-8c08-1119c14ba9c0.png)

**Comment by boltgolt** [comment]
Text at the bottom is just OpenCV debug text, doesn't really matter at all. The window will be as big as your webcam resolution so resizing is unnecessary. 

This is a lot of issues for just one person to open

**Comment by leoheck** [comment]
> This is a lot of issues for just one person to open
Yeap, it is necessary when the software is not working as described.

**Comment by boltgolt** [comment]
Completely the wrong mindset when using a free, open source project.

**Comment by leoheck** [comment]
> Completely the wrong mindset when using a free, open source project.

I can say the same to you when you said something like this `This is a lot of issues for just one person to open`

**Comment by boltgolt** [comment]
If only you posted things that weren't posted in other issues already that would be fine. Fortunately I don't _have_ to deal with entitled people here
