### ISSUE TITLE
The login keyring did no get unlocked.

### ISSUE THREAD

**Issue by leoheck** [boltgolt/howdy#500]
On Ubuntu 20.10 I am seeing this. 
Any idea on how to fully unlock the system? Am I missing something or doing anything wrong?
![image](https://user-images.githubusercontent.com/1277920/104974428-bfc27e00-59d6-11eb-8fe4-694c89cdcdd5.png)

**Comment by boltgolt** [comment]
Please search for an issue first, see #438
