### ISSUE TITLE
Do not use howdy to unlock system for the first unlock after boot on Deepin

### ISSUE THREAD

**Issue by forliuyifei** [boltgolt/howdy#509]
As the title says, if you use howdy instead of password to log in for the first unlock after booting, it may cause some strange problems.

 Even if I have passed theface recognition, my Deepin system will still pop up the key ring unlocking window, and the WiFi that has saved the password will also repeatedly ask me to enter the password. In addition, the login status of my Deepin account has also disappeared.

If I manually cover the camera and use the keyboard to enter the password, the above situation will not happen again.

**Request:**

So can you add an option so that the original password must be used to unlock the first unlock to avoid that annoying bug.

Thank you for your contribution, now Linux can be as suitable for daily use as Windows.

**Comment by boltgolt** [comment]
Thanks for the kind words! This issue has been open many, many times, checkout #503
