### ISSUE TITLE
/lib/security/howdy/dlib-data

### ISSUE THREAD

**Issue by Yin-Chen-0** [boltgolt/howdy#516]
When I follow the step to install on Ubuntu 20.04, I met the error as followed.  
>>> Downloading and unpacking data files

Downloading 3 required data files...
Unpacking...
bzip2: Can't open input file *.bz2: No such file or directory.
Error while running last command
dpkg: 处理软件包 howdy (--configure)时出错：
 已安装 howdy 软件包 post-installation 脚本 子进程返回错误状态 1
正在处理用于 libc-bin (2.31-0ubuntu9.2) 的触发器 ...
/sbin/ldconfig.real: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_
train.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_
infer.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_
infer.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_
train.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_
infer.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_
train.so.8 is not a symbolic link

正在处理用于 man-db (2.9.1-1) 的触发器 ...
在处理时有错误发生：
 howdy
E: Sub-process /usr/bin/dpkg returned an error code (1)

I use the 'sudo apt install howdy' to install the howdy,but a error happened. I have tried to download the three data files manually and moved them to /lib/security/howdy/dlib-data/ . But it still don't work for me.What should i do, can you give me some suggestions? Thanks!

**Comment by boltgolt** [comment]
Following up on the data file download at #512, that issue seems to have started yesterday. It seems like you have errors in you cuda compilation, do you have a nvidea GPU installed?
