### ISSUE TITLE
IR Emitter Led

### ISSUE THREAD

**Issue by BierDav** [boltgolt/howdy#520]
I know that there are many other issues about similar topics but I think that one fixed it really:

I have a Lenovo E15 with IR Emitter. My IR Emitter is working because on Windows it worked.
It seems that my cam is also working on ubuntu with `sudo howdy test`  even though the picture is only black. I can see 30 fps tag and really small  image changes. So it's obvious that the problem is my IR Emitter Led which is not turning on.

Simple Question:
How to say Howdy to turn on the IR Emitter Led

Nice day,
BierDav

**Comment by EmixamPP** [comment]
Hello, go have a look on my repo : https://github.com/EmixamPP/linux-enable-ir-emitter.
I think you will find your answer, there everything is explained.
I remain available if you need help :smiley:
