### ISSUE TITLE
Removing software while camera is in use causes an infinite loop

### ISSUE THREAD

**Issue by 4a454646** [boltgolt/howdy#530]
1. Have your camera already in use from an application like Zoom or Discord.
2. Perform an action that brings up Ubuntu's GUI authentication, such as trying to remove software.

This results in an infinite loop of failed authentication with no opportunity to enter your password (see attached video). 
Linux distro: Ubuntu 20.04 LTS
Howdy version: Howdy 2.6.1

Video:
https://user-images.githubusercontent.com/46868596/114211526-9b12de00-9915-11eb-8e41-f64eade24d94.mp4

**Comment by boltgolt** [comment]
Is howdy your only authentication option? Does this also show up in other places like sudo when your camera is used by zoom/discord?

**Comment by 4a454646** [comment]
Yes, I have Howdy as the main authenticator, and if it fails I just use the normal password enter. The only places this occurs is when the GUI authentication field is brought up (removing software and trying to perform file operations as admin). There are probably other things that cause the GUI to pop up, but I haven't encountered them yet.

**Comment by boltgolt** [comment]
This sounds more like a PAM issue with your GUI implementation. My advice would be to follow [this guide](https://github.com/boltgolt/howdy/wiki/Only-using-howdy-for-specific-authentication-types) to only use Howdy where PAM is not buggy
