### ISSUE TITLE
howdy test segment violation

### ISSUE THREAD

**Issue by zago88** [boltgolt/howdy#54]
On excute howdy test fail with output

```
Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

QObject::moveToThread: Current thread (0x8fc4420) is not the object's thread (0x91c03a0).
Cannot move to target thread (0x8fc4420)

Violación de segmento  
```

----

**Kubuntu 18.04**:
**Howdy 2.3.0**:
**Python 3.6.5**.

**Comment by zago88** [comment]
Thanks for the answer, This exceed my knowledge since the problem is the opencv library directly,  I'll try to investigate how to patch this issue with the namespace on Qt platform

**Comment by antonio-petricca** [comment]
Hi, I have the same issue on Linux Mint 19.3 (Ubuntu 18.04).

Any solution yet?
