### ISSUE TITLE
Howdy printing a ton of info while running.

### ISSUE THREAD

**Issue by rohittp0** [boltgolt/howdy#553]
After installing howdy It was not being used for sudo and log in. I solved this ( for sudo only ) by following https://github.com/boltgolt/howdy/issues/233#issuecomment-557154139 this instruction. Now, whenever I use sudo it ideles for like 10-15 seconds and then prints a ton of info to the terminal. Is there some way to disable this?
  
  The problem with howdy taking time to start is reduced the next time I use it in the same terminal. For example, it usually takes about 20 seconds to run first. The from the next run downwards it takes around 10 seconds from start to end.

   I haven't yet figured out a way to use howdy on the login screen, If someone has any solution please let me know. 

### Sample output

> sudo -k ls                           
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/videoio_registry.cpp (217) VideoBackendRegistry VIDEOIO: Enabled backends(9, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); V4L2(960); CV_IMAGES(950); CV_MJPEG(940); FIREWIRE(930); UEYE(920)
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (324) getPluginCandidates VideoIO plugin (FFMPEG): glob is 'libopencv_videoio_ffmpeg*.so', 1 location(s)
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (331) getPluginCandidates     - /lib64: 0
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (335) getPluginCandidates Found 0 plugin(s) for FFMPEG
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/cap_gstreamer.cpp (831) open OpenCV | GStreamer: /dev/video0
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/cap_gstreamer.cpp (864) open OpenCV | GStreamer: mode - FILE
> [ WARN:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/cap_gstreamer.cpp (2056) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
> [ WARN:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/cap_gstreamer.cpp (1034) open OpenCV | GStreamer warning: unable to start pipeline
> [ WARN:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/cap_gstreamer.cpp (597) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (324) getPluginCandidates VideoIO plugin (INTEL_MFX): glob is 'libopencv_videoio_intel_mfx*.so', 1 location(s)
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (331) getPluginCandidates     - /lib64: 0
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (335) getPluginCandidates Found 0 plugin(s) for INTEL_MFX
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (324) getPluginCandidates VideoIO plugin (MSMF): glob is 'libopencv_videoio_msmf*.so', 1 location(s)
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (331) getPluginCandidates     - /lib64: 0
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/videoio/src/backend_plugin.cpp (335) getPluginCandidates Found 0 plugin(s) for MSMF
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/core/src/parallel/registry_parallel.impl.hpp (96) ParallelBackendRegistry core(parallel): Enabled backends(2, sorted by priority): TBB(1000); OPENMP(990)
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/core/include/opencv2/core/parallel/backend/parallel_for.tbb.hpp (54) ParallelForBackend Initializing TBB parallel backend: TBB_INTERFACE_VERSION=11103
> [ INFO:0] global /builddir/build/BUILD/opencv-4.5.2/modules/core/src/parallel/parallel.cpp (77) createParallelForAPI core(parallel): using backend: TBB (priority=1000)
> Data	 Documents  Music     Public	 Videos
> Desktop  Downloads  Pictures  Templates  zsh_history
> 

----

Linux distribution (if applicable): Fedora 34

Desktop Environment: Gnome 40

Display Manager: GDM

Howdy version (`sudo howdy version`): Howdy 2.6.0

----

Adding the output of sestatus just in case it may be used to resolve not working on login screen,

SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

**Comment by boltgolt** [comment]
Please use the search function before opening an issue, take a look at #353
