### ISSUE TITLE
Login keyring did not get unlocked when I (Howdy), logged in [Ubuntu 20.04.2 LTS]

### ISSUE THREAD

**Issue by HorseboxHeaven** [boltgolt/howdy#554]
When I run a sudo command, Howdy recognizes me and provides the password. I have created 6 face models and Howdy seems to work pretty well in different light levels and face angles, except for one thing. Howdy allows the PC to complete the boot and load the desktop. The startup applications load, and then I get an authentication prompt advising me that the login keyring did not get unlocked when I (Howdy), logged in.  So after all, I still need to use my password to access the PC.  Here's what I see. 

![Screenshot from 2021-06-07 16-06-39](https://user-images.githubusercontent.com/4005326/121100962-c8371c00-c7f2-11eb-9dcc-a950a4a7b8f0.png)

**Comment by boltgolt** [comment]
Doesn't happen on every installation, only when using programs that actually utilize the keyring like chrome

**Comment by HorseboxHeaven** [comment]
I'm not using Chrome. Or do you mean when Chrome is simply installed on the machine?

**Comment by boltgolt** [comment]
It just has to be installed and there are quite a few other programs that use it. It's a bit besides the point though, if I listed all possible complications on the readme it would be 4 times as long
