### ISSUE TITLE
Integration with KWallet

### ISSUE THREAD

**Issue by bangar1991** [boltgolt/howdy#56]
Just installed Howdy on Manjaro, and was able to setup everything fairly easily by following the ArchWiki instructions. My use case is to just use howdy at the graphical login screen. So, I've modified `/etc/pam.d/sddm` like (hope it's the correct thing to do): 
```
auth            sufficient      pam_python.so /lib/security/howdy/pam.py
auth		include		system-login
auth		optional	pam_kwallet5.so
account		include		system-login
password	include		system-login
session		include		system-login
session		optional	pam_kwallet5.so auto_start
```
I can now login without password. However, soon after login, KDE Wallet prompts for a password, which kind of defeats the purpose of having face authentication. I think the default configuration in Manjaro is for KDE Wallet to use the same password as the one used for login. Perhaps that's why it never prompts for one when I'm using the usual password authentication.

How could Howdy be better integrated with pam_kwallet5, so that Howdy's authentication would be accepted by KWallet as well? Alternatively, is it possible to change the `sddm` configuration somehow to achieve the same? Since I don't know about the underlying details, I wasn't sure if this should be posted as a bug or a feature request, so sorry if I posted at the wrong place. I'd be happy to repost under the correct section if needed.

**Comment by boltgolt** [comment]
I have very little knowledge of arch, but i'm guessing that KDE Wallet is the equivalent of Gnome Keyring on Ubuntu. Keyring stores all saved passwords in encrypted form on disk. The reason this will always prompt for a password is that your login password is also the encryption key, without it no saved passwords can be read.

There is a solution, but it's an absolute security nightmare. By setting an empty password for the keyring you store the passwords in plain text and thus eliminate the need for a password on login. A very heavy trade of between speed and security.

**Comment by bangar1991** [comment]
Thanks for you response. It's surely not a good idea to ask KDE Wallet to store passwords in plain text :) Unfortunately, this means that it's going to be difficult to use Howdy in my scenario. In any case, I thank you for such a nice software. Hope you continue the good work!

**Comment by KelleyMcChes** [comment]
The information in the [ArchWiki entry for KDE Wallet](https://wiki.archlinux.org/index.php/KDE_Wallet) might work for you @bangar1991. 

It seems you will need to install `kwallet-pam` with no further configuration (as long as you haven't removed any lines from `/etc/pam.d/sddm`)

**Comment by bangar1991** [comment]
@KelleyMcChes Thanks for your comment. `kwallet-pam` is installed by default on my system and PAM configuration is setup correctly as well. The problem, I think, is when I login using howdy and don't enter the login password, `kwallet-pam` authentication module is not even invoked (howdy is set as sufficient). Even if it did get invoked somehow, it relies on its master password being the same as login password so that when login password is entered, KDE wallet is unlocked automatically. Since I don't enter any, it remains locked.

This is based on my limited understanding of PAM. Feel free to correct me of course.

**Comment by boltgolt** [comment]
I think you're correct, especially after reading "The wallet cannot be unlocked when using autologin." on that wiki page. There's no real way around this except storing the password within howdy, which is a liability i do not want to have.
