### ISSUE TITLE
Support for Raspbian? 

### ISSUE THREAD

**Issue by swordsmanr** [boltgolt/howdy#57]
I'd love to have this for my Raspberry Pi - but when I run 

`sudo add-apt-repository ppa:boltgolt/howdy`

I get "Error: could not find a distribution template for Raspbian/stretch"

Should this project work on Raspberry Pi? If not, is that an option that could be investigated? Thanks!

**Comment by boltgolt** [comment]
There's no ARM support at the moment. I don't think a lot of people have both an ARM possessor and an IR camera, so unfortunately i won't be working on this.

However, if you have some xperience with python and debian you should be able to install Howdy from source. Take a look at the `debian/postinst` file which contains the automatic installation instructions.
