### ISSUE TITLE
Any influence of changing dark_threshold?

### ISSUE THREAD

**Issue by KairuiLiu** [boltgolt/howdy#575]
Hi, the environment of mine may be a little dark ([average 93]) 
Thus, I modified the dark_threshold from 50 to 100. 
I'm a new commer of CV, and do not know positive and negative effects...
Thanks a lot for your helpping :-)

---

by the way, I found for KDE to disable Howdy in the first login,
we can just modify `/etc/pam.d/kde`, and no need for (/etc/pam.d/\*login\* or /etc/pam.d/\*system\*)

**Comment by boltgolt** [comment]
Basically there are no downsides for your specific setup if you set it to 100. The config option is meant to help performance on more typical Windows Hello cameras. These cameras have blinking LED lights that light up every other frame, leaving 50% of frames so dark that no detection could succeed. By filtering out these frames performance is therefore doubled.

Setting it to 100 (disabling it) is probably the best for your setup as you do not seem to have this blinking issue.
