### ISSUE TITLE
Does not unlock with glasses, works fine without

### ISSUE THREAD

**Issue by vexersa** [boltgolt/howdy#576]
Thanks for the cool app!

Is there something I'm missing for getting Howdy to work when I'm wearing glasses? 

Works fine without them, using either IR or normal webcam on my MS Surface Laptop 3.

**Comment by boltgolt** [comment]
Yes, as I have glasses too I would suggest adding a model of your face with glasses on too. Just running `howdy add` again will let you add a second model

**Comment by vexersa** [comment]
I have attempted this, but the unlock does not function.

Are there any logs I can provide?
