### ISSUE TITLE
Costomize howdy to use only in lockscreen

### ISSUE THREAD

**Issue by Alexhhhc** [boltgolt/howdy#578]
Since howdy doesn't work well with keyring,can you set a option to allow it only in lockscreen,not in login interface?Thanks for your great work.

**Comment by boltgolt** [comment]
Take a look at [this wiki page](https://github.com/boltgolt/howdy/wiki/Only-using-howdy-for-specific-authentication-types)

**Comment by Alexhhhc** [comment]
I use arch Linux and I have tried that manually.(arch Linux won't configure it by default)I have tried different files but it doesn't meet my expectations.

**Comment by boltgolt** [comment]
In what way does it not meet your expectations?
