### ISSUE TITLE
sudo: howdy: command not found

### ISSUE THREAD

**Issue by AryanJha123** [boltgolt/howdy#583]
Any command that has to do with howdy (other than man howdy) seems to not work. For example, when I do "sudo howdy config", all I get is "sudo: howdy: command not found"
----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Lubuntu 19.04, which is based on Ubuntu 21.04

Howdy version (`sudo howdy version`): can't check, but downloaded it last night.

**Comment by AryanJha123** [comment]
Never mind, apparently there was a similar issue.

**Comment by boltgolt** [comment]
Thanks for finding the other issue yourself!
