### ISSUE TITLE
[feature request] Howdy multi-factor authentication

### ISSUE THREAD

**Issue by blamster19** [boltgolt/howdy#584]
During installation and later through the config, user should be able to decide whether they want to replace current password with face recognition or keep the password and use Howdy as another security layer. In case of failure, the user should be prompted to enter second password given during configuration.

**Comment by boltgolt** [comment]
One of the [wiki pages](https://github.com/boltgolt/howdy/wiki/Only-using-howdy-for-specific-authentication-types) explains parts of how to change PAM.

The goal of Howdy is to speed up logging in wile not lowering security too much. This is why Howdy is `sufficient` in PAM by default, and why there is no configuration option. However, maybe it would be nice to have a dedicated wiki page explaining how to configure Howdy for the other setups you mentioned
