### ISSUE TITLE
show webcam preview on login screen when using Howdy

### ISSUE THREAD

**Issue by shahulhameed8** [boltgolt/howdy#588]
I just want a live preview of the webcam on the login screen for convenience while using howdy?

**Comment by boltgolt** [comment]
In 3.0.0 there will be an overlay telling you exactly what Howdy is doing, but without a video preview. Implementing a preview would require more processing, lowering frame rate and this slowing down detection. Not sure that's worth it

**Comment by shahulhameed8** [comment]
Thanks for the response.
