### ISSUE TITLE
Fedora 35 Beta

### ISSUE THREAD

**Issue by logicito** [Boltgolt/howdy#595]
I installed Howdy on Fedora 35 Beta, when authenticating via sudo I get the following messages:

libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
MFX: Can't initialize session

it works, but I don't like the messages, any advice how to get rid of them?

**Comment by realcomplex** [comment]
For what it's worth, I followed the trail to https://github.com/opencv/opencv/issues/17221, and a fix suggested there does get rid of the annoying warnings. Specifically, set `OPENCV_VIDEOIO_PRIORITY_INTEL_MFX=0`. (To make persistent, add `export OPENCV_VIDEOIO_PRIORITY_INTEL_MFX=0` to `~/.profile` or equivalent.)

**Comment by rokejulianlockhart** [comment]
@boltgolt, doesn't https://github.com/boltgolt/howdy/issues/595#issuecomment-964224376 demonstrate otherwise?

**Comment by boltgolt** [comment]
Otherwise than what?

**Comment by rokejulianlockhart** [comment]
@boltgolt, I don't know. Apologies. I still can't discern what I was referencing.
