### ISSUE TITLE
Howdy stops working after suspending

### ISSUE THREAD

**Issue by FelixTheTBone** [Boltgolt/howdy#601]
Hi there, many thanks for creating this amazing tool!
I tried to find this on the already listed issues but could not find something similar:
Howdy works very well from booting, however, when I suspend and resume my laptop it seems to stop working.
When hibernating and resuming, Howdy keeps working just fine though.
Is this a known issue and is there a way to restart Howdy after suspending / resuming?
Thank you.

**Comment by boltgolt** [comment]
If you want to it might be good to add it to https://github.com/boltgolt/howdy/wiki/Common-issues
