### ISSUE TITLE
module dlib not found

### ISSUE THREAD

**Issue by kuba21333** [boltgolt/howdy#602]
Howdy is set up but when i try to do sudo -i it says that dlib isnt installed while it is. I tried chmoding howdy but no success.

`[Wiertelus@milosc-do-salatki-i-do-twojej-matki ~]$ sudo -i
Traceback (most recent call last):
  File "/lib64/security/howdy/compare.py", line 17, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'
`

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Fedora 35 beta

Howdy version (`sudo howdy version`): Howdy 2.6.1

**Comment by perceival** [comment]
You need to install python3-dlib instead:
`sudo dnf -y install python3-dlib`

**Comment by kuba21333** [comment]
> You need to install python3-dlib instead: `sudo dnf -y install python3-dlib`

Thanks! that worked
