### ISSUE TITLE
issue while ( sudo howdy add )

### ISSUE THREAD

**Issue by cg-mitun-akil** [boltgolt/howdy#615]
![image](https://user-images.githubusercontent.com/78992845/142441393-fc73997f-2363-43ea-856a-f0785a9aecb9.png)
please help with this issue

**Comment by boltgolt** [comment]
Rule of thumb for anything linux: If it returns permission denied you probably need elevated privileges. Run it as root, aka use `sudo`

**Comment by boltgolt** [comment]
While i'm at it, please post errors as text, not as a screenshot. If it's text other people with the same issue can find it through search
