### ISSUE TITLE
Should the circle become green during recognition test?

### ISSUE THREAD

**Issue by highfreq** [boltgolt/howdy#617]
Should the circle turn green during a test recognition? Mine is always red, already rised param to 5 for a more relaxed setting but still red.
It is on ubuntu 21.10 impish

**Comment by EmixamPP** [comment]
No don't worry, the circle is always red.

**Comment by boltgolt** [comment]
Probably good to add at some point but as @EmixamPP said it currently doesn't take any face models into consideration
