### ISSUE TITLE
Non root/pam usage

### ISSUE THREAD

**Issue by guibou** [boltgolt/howdy#620]
I'd like to use howdy not to unlock my computer, but instead to conditionally lock it.

The idea is to regularly (every 10s) check if I'm still in front of the computer and if not, lock it, by calling my screen locker.

So I don't need system configuration, pam, root access. I just need to:

- config file in user directory
- register a face locally for my user
- call howdy, without root access and let it return a different exit code depending on if I was recognized or not.

**Comment by boltgolt** [comment]
Although this is unsupported, this is exactly what calling compare.py will do. It will return error code 0 if authentication succeeded
