### ISSUE TITLE
Error: Sub-proccess /usr/bin/dpkg returned an error code (1) 

### ISSUE THREAD

**Issue by TomYoungs** [boltgolt/howdy#626]
Howdy!
Not sure why but when i try to install (with PopOS) i keep getting this issue when trying to install, any ideas?

![Screenshot from 2021-12-23 15-40-08](https://user-images.githubusercontent.com/60447023/147262502-35d679a9-df66-4cb1-aa65-c33ea65d0635.png)

**Comment by boltgolt** [comment]
Please use the search function before opening a new issue, more details about this issue can be found in quite a few issues like #598. Additionally, please don't post screenshots of errors as that makes them unsearchable
