### ISSUE TITLE
Camera will change from IR sometimes.

### ISSUE THREAD

**Issue by Rhiyo** [boltgolt/howdy#63]
Sometimes the camera howdy uses will switch to the normal camera, and then after a few days it will switch back to the IR camera. I have no idea what could be causing this, I imagine it's something to do with the laptop firmware itself?

I'm using a HP Envy x360 13.3 with a Ryzen 2500u.

It's done this under the Pop!_OS and Linux Mint under the Linux Kernel 4.17 and 4.18

----
Pop!_OS
Latest as of this post

**Comment by boltgolt** [comment]
Could your run `ls /dev/ | grep video` for me?

**Comment by Rhiyo** [comment]
I get:
video0
video1
video2
video4

**Comment by Rhiyo** [comment]
It's just happened again, the IRCamera is now video2.

I haven't really checked but I'm pretty sure it only happens between reboots.

**Comment by boltgolt** [comment]
I'm guessing your webcam is connected internally as an USB webcam, and USB devices can be assigned device IDs in almost random order. This could be fixed by using the hard coded ID from the USB interface instead, i'll look into it.

**Comment by boltgolt** [comment]
The last release changed the way Howdy picks a camera, and now uses the PCI id of the USB device to determine which camera to use. This should fix your problem.

When upgrading from 2.3.1 to 2.4.0 the installer will automatically convert your old `device_id` to a `device_path`, but you might want to replace that path with the correct camera in `/dev/v4l/by-path/`.
