### ISSUE TITLE
KDE Wallet question

### ISSUE THREAD

**Issue by dm30** [boltgolt/howdy#634]
Hi. During installation KDE Wallet asks for creating a 'wallet' but tells a password was not set. As I'm using Ubuntu, the password manager is GNOME's and seems its not checked. But I can use Howdy normally. Can that be an issue?

I took some snapshots (excuse they are in spanish. I hope its easily understandable)
Thank you.

![Captura de pantalla de 2022-02-06 17-57-17](https://user-images.githubusercontent.com/8088390/152692396-9cd679b8-957e-4162-93ca-e5fa68344fd0.png)
![Captura de pantalla de 2022-02-06 17-58-06](https://user-images.githubusercontent.com/8088390/152692404-88cfd077-f9df-4e0a-aff5-e6a566ae88a2.png)
u

**Comment by boltgolt** [comment]
Problem with Howdy is that it can't unlock your keychain as you never enter your password, which is used to unencrypt your keychain. One solution would be to not use Howdy for your login

**Comment by nalin29** [comment]
Alternatively you could set the keychain to empty then it will automatically unlock. But that is living dangerously.

**Comment by dm30** [comment]
Thank you. But I don't understand. Is this normal behavior or I shouldn't care? Howdy seems to work normally.

**Comment by boltgolt** [comment]
Basically there's a concept in Ubuntu (and other distros of course) called a "keychain" that contains secret passwords and is encrypted on disk. To unlock this chain and use the secrets it needs you login password. When you login with Howdy you don't provide your password at all and thus your keychain can't be unlocked. 

If that's fine with you you can keep it like this. To fix it you can disable Howdy for logging in, or live your life very dangerously and set an empty password for you keychain as @nalin29 said

**Comment by nalin29** [comment]
Only if it bothers you it’s normal behavior. But you would have to unlock the keychain for certain things such as Wi-Fi passwords.
