### ISSUE TITLE
 Unable to install howdy under Ubuntu 21.10

### ISSUE THREAD

**Issue by sushan1223** [boltgolt/howdy#638]
![Screenshot from 2022-02-21 00-17-58](https://user-images.githubusercontent.com/61424528/154858250-a66d19c0-44a9-48de-99c4-92fc26823768.png)

**Comment by boltgolt** [comment]
Seems like you have a very broken package registry, can you run `sudo apt-get update --fix-missing`? Also, please paste console output into github in stead of a screenshot so others can also find this issue too

**Comment by harivamsi9** [comment]
**Tested on Ubuntu 21.10, Installation was success.**
Followed the instructions given in README.md file

`sudo add-apt-repository ppa:boltgolt/howdy
`
`sudo apt update
`
`sudo apt install howdy`
Attaching screenshots for your reference - 
<img width="960" alt="01" src="https://user-images.githubusercontent.com/44733128/159551666-161b5d99-a150-4968-9a8c-3f5f3074dc01.PNG">

<img width="929" alt="02" src="https://user-images.githubusercontent.com/44733128/159551699-4836fca9-dd76-498d-93aa-316cbea164a0.PNG">


<img width="935" alt="03" src="https://user-images.githubusercontent.com/44733128/159551719-e1795334-19fd-4859-a7eb-2a63c40264e8.PNG">


<img width="927" alt="final" src="https://user-images.githubusercontent.com/44733128/159551732-90930867-165c-40b7-b7f2-b4e05c357b1c.PNG">


Text File of Output for reference:
[howdy_installation.txt](https://github.com/boltgolt/howdy/files/8327144/howdy_installation.txt)

**Comment by harivamsi9** [comment]
@sushan1223 usually 

> <package> but is not installable
these occur when the <package> itself is not present in the ubuntu universal repo, I checked the repo, and these dependencies which ever were shown in your output are all present and compatible only.
So the only explanation is that you may have to update `sudo apt update` and fix broken `sudo apt-get update --fix-missing`
these should fix.

**Comment by boltgolt** [comment]
No response from OP, seems like a broken registry
