### ISSUE TITLE
Accept Doas as an alternative to Sudo

### ISSUE THREAD

**Issue by Larsenist** [boltgolt/howdy#642]
Even with root privileges howdy doesn't let us use its commands unless you use sudo. Adding a variable in the config file for it would be great. It would also be helpful to show the config path when you get the message about needing elevated permissions.

**Comment by boltgolt** [comment]
Very good point, Howdy should really just check if it has the permissions it needs in stead of relying on a environment variable

**Comment by TheHighGroundWins** [comment]
same I agree with this. having sudo just for howdy feels strange.
