### ISSUE TITLE
Howdy crash report on Ubuntu 22.04

### ISSUE THREAD

**Issue by cccaballero** [boltgolt/howdy#655]
Using Ubuntu 22.04 the face recognition works, but I am getting a Howdy related system crash report

![Captura desde 2022-04-24 03-26-41](https://user-images.githubusercontent.com/3727802/164965189-0d9f7341-4d91-4fe8-8fdd-23de1cbaa009.png)

**Comment by boltgolt** [comment]
Did recognition succeed? Should not work if you're missing dlib 

Search other issues and you'll find plenty of others with missing dlib dependencies

**Comment by boltgolt** [comment]
For example #648

**Comment by cccaballero** [comment]
I have not had the problem again, I had just updated from 20.04 and reinstalled howdy, it is possible that the error was from before reinstalling howdy and Ubuntu has shown the reports with some delay

**Comment by Sciroccogti** [comment]
So a reinstallation is a must, right?

**Comment by boltgolt** [comment]
it seems that way
