### ISSUE TITLE
Cannot install howdy: FileNotFoundError: [Errno 2] No such file or directory: 'pip3'

### ISSUE THREAD

**Issue by MrConorAE** [boltgolt/howdy#658]
While installing Howdy, dpkg returns a non-zero exit code and prints the following traceback:
```
Traceback (most recent call last):
  File "/var/lib/dpkg/info/howdy.prerm", line 45, in <module>
    subprocess.call(['pip3', 'uninstall', 'dlib', '-y', '--no-cache-dir'])
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip3'
```

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu 21.10

Howdy version (`sudo howdy version`): 2.6.1
Note: `howdy` command does not work due to failed install.

I also can't remove it, because the pre-remove script crashes with the same error.

**Comment by boltgolt** [comment]
Please use the search function: #598
