### ISSUE TITLE
Howdy not working

### ISSUE THREAD

**Issue by Piotr0305** [boltgolt/howdy#665]
_Please describe the issue in as much detail as possible, including any errors and traces._
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

How I wanted to run 'sudo howdy test' it appeared to me:

`Traceback (most recent call last):
  File "/usr/bin/howdy", line 109, in <module>
    import cli.test
  File "/usr/lib/security/howdy/cli/test.py", line 17, in <module>
    config.read(path + "/../config.ini")
  File "/usr/lib/python3.10/configparser.py", line 698, in read
    self._read(fp, filename)
  File "/usr/lib/python3.10/configparser.py", line 1086, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/usr/lib/security/howdy/cli/../config.ini', line: 5
'dismiss_lockscreen = true\n'
`

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Manjaro Linux

Howdy version (`sudo howdy version`): 2.6.1

**Comment by boltgolt** [comment]
Your config file is malformed: "File contains no section headers."

Please fix the file yourself or purge and reinstall Howdy to get a fresh one
