### ISSUE TITLE
GStreamer error on startup

### ISSUE THREAD

**Issue by karlettoh** [boltgolt/howdy#67]
First off, apologies if this is a symptom but not the cause and I need to fire this question elsewhere.

When I attempt to test, I can see the camera feed after this error. This same error occurs on login as the IR sensor initialises. It doesn't automatically log me in and so I assume this is the cause below.

OS - Arch
Machine - HP Envy x360 

Anything I can provide to help. let me know!

## example

```sudo howdy test
[sudo] password for user: 

(python3:2072): GStreamer-CRITICAL **: 16:17:07.864: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode```

**Comment by boltgolt** [comment]
Could you try running `sudo apt install libv4l-dev`? Looks like your camera can't be opened by OpenCV

**Comment by karlettoh** [comment]
```pacman -S v4l-utils
warning: v4l-utils-1.14.2-1 is up to date -- reinstalling```

Already had it, unfortunately. Perhaps there's another dependency I'm missing

**Comment by boltgolt** [comment]
Is the image it in color or black and white?

Frame capture seems to be working, so adding faces and detecting them on login should work normally. You could try upping the `certainty` value in `sudo howdy config`.

**Comment by karlettoh** [comment]
It's black and white. I've tried all 4 devices just to rule them out.
I've added faces successfully. 

Upped the certainty to 5 and it logged me in.
