### ISSUE TITLE
libprotobuf.so.30: cannot open shared object file

### ISSUE THREAD

**Issue by cog25** [boltgolt/howdy#670]
_Please describe the issue in as much detail as possible, including any errors and traces._
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

When i try to add my face or run `howdy test`, this error appeared
```
Traceback (most recent call last):
  File "/usr/bin/howdy", line 95, in <module>
    import cli.add
  File "/usr/lib/security/howdy/cli/add.py", line 11, in <module>
    from recorders.video_capture import VideoCapture
  File "/usr/lib/security/howdy/recorders/video_capture.py", line 6, in <module>
    import cv2
ImportError: libprotobuf.so.30: cannot open shared object file: No such file or directory
```

I tried `howdy`, `howdy-git` in aur, but they both didn't work.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Arch Linux

Howdy version (`sudo howdy version`): 2.6.1

**Comment by boltgolt** [comment]
Seems like a dlib compilation issue, could you try reinstalling dlib?
