### ISSUE TITLE
I can help with translate

### ISSUE THREAD

**Issue by bpavuk** [boltgolt/howdy#677]
Hi, boltgolt. I like to using Howdy auth. It has sent to the russian warship a couple of problems (I like to use big strange hard passwords). But, I have'nt seen russian or Ukrainian language support. I can help you with translating to those languages. It will make this tool really popular, and we'll make our contribution to war between Linux and Shindows (only native face id and games are things that Linux really need to win).

**Comment by bpavuk** [comment]
Write me if you'll need my help boopentiy@gmail.com

**Comment by boltgolt** [comment]
You can! Checkout the pinned issue at #486

**Comment by boltgolt** [comment]
As of right now, the russian translation is done but the ukrainian needs a lot more help

**Comment by bpavuk** [comment]
Send me what to translate. I'll send you translated text

вс, 12 июн. 2022 г. в 14:51, boltgolt ***@***.***>:
