### ISSUE TITLE
Can we disable the face ID when installing or when requesting permissions on terminal 

### ISSUE THREAD

**Issue by merouaneamqor** [boltgolt/howdy#682]
when i tried to install a new software on my laptop ( that normally request a sudo password ) it got installed just using my face ID and that can be dangerous !!!
any malware can get a sudo permission and get to any file on my system

**Comment by boltgolt** [comment]
Well, that's what face authentication does. [Read this wiki page](https://github.com/boltgolt/howdy/wiki/Only-using-howdy-for-specific-authentication-types) to select specific PAM files to enable Howdy in
