### ISSUE TITLE
Can't add face model

### ISSUE THREAD

**Issue by Jaydenha09** [boltgolt/howdy#685]
I am using ubuntu 22.4
But I can't add face model

`Camera path is not configured correctly, please edit the 'device_path' config value.
Exception ignored in: <function VideoCapture.__del__ at 0x7f55b999c670>
Traceback (most recent call last):
  File "/usr/lib/security/howdy/recorders/video_capture.py", line 55, in __del__
    self.internal.release()
AttributeError: 'VideoCapture' object has no attribute 'internal'
`

**Comment by boltgolt** [comment]
https://github.com/boltgolt/howdy/wiki/Common-issues#error-when-trying-to-add-a-face-model
