### ISSUE TITLE
Howdy to automatically switch between different cameras.

### ISSUE THREAD

**Issue by achidipothu** [boltgolt/howdy#686]
When I use laptop camera, howdy works great and when I dock it up.  I use an external HDMI monitor based camera and at this time I usually keep the lid of the laptop closed and so the earlier camera is not available. Howdy goes by the config and still tries with the laptop camera and fails.

If I do a **sudo howdy config** and change the device_path to HDMI based camera and howdy starts working again.

It will be great if howdy can switch between available cameras automatically, with out users having to change the config every time, may be it can take two device paths in the config and try both of them.

**Comment by boltgolt** [comment]
Please use the search function and take a look at #515
