### ISSUE TITLE
Howdly doesn't work at the login 

### ISSUE THREAD

**Issue by YulBrinner90** [boltgolt/howdy#697]
Hi,

Howdly works fine at the start, after the restart, after the suspension (or lockscreen) but not after the logout (Ubuntu 22.04). It works at the beginning, to be more precise, but immediatly after Gnome demands me an "authentication request". So I have to type the password manually. I have added the line "auth sufficient pam_python.so /lib/security/howdy/pam.py" at the end of each file in /etc/pam.d but unsuccesfully.

Thanks in advance

**Comment by boltgolt** [comment]
So the problem here is that Howdy works fine, but you have passwords or other secrets saved in your keyring that are encrypted with your password. Gnome can't decrypt this without you entering your password first, nothing Howdy can do about that in a secure way. See #438

**Comment by YulBrinner90** [comment]
Thanks. Sorry for the duplication of the post.
