### ISSUE TITLE
sudo doesn't work

### ISSUE THREAD

**Issue by wuqso** [boltgolt/howdy#701]
I Installed howdy on my Fedora linux 36 system and everything was fine. I could run sudo -i with facial identification.

Then I used the compare.py to replace that in /lib64/security/howdy and added

`auth sufficient pam_python.so /lib64/security/howdy/pam.py`

into /etc/authselect/system-auth, and run the command

`sudo chmod -R 755 /lib64/security/howdy`.

Now I cannot run sudo. Each time I run sudo I have

```
  File "/lib64/security/howdy/compare.py", line 67
    <title>howdy/compare.py at caf244ce297d27d40168c40571b0fad6f7ee2596 · boltgolt/howdy</title>
                                                                        ^
SyntaxError: invalid character '·' (U+00B7)
Unknown error: 1
[sudo] password for ***: 
sudo: PAM authentication error: Unknown error -1
sudo: a password is required
```

What can I do now?

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Fedora 36

Howdy version (`sudo howdy version`):

**Comment by boltgolt** [comment]
Your compary.py is a HTML page? What did you do?

**Comment by wuqso** [comment]
My computer has dual system. So I installed a btrfs driver in windows, changed the compary.py and  /etc/authselect/system-auth to the original ones. Then sudo can work now.

**Comment by boltgolt** [comment]
Good fix, but i don't understand why there was HTML in that critical file. Don't download pages into critical scripts i guess.
