### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by saltedcoffii** [boltgolt/howdy#705]
This occurs:
```
$ sudo howdy test
[1]    68221 illegal hardware instruction  sudo howdy test
```

I am unsure how to provide logs or similar for this issue. Please give me commands or files to upload that may help you!

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Arch Linux rolling

Howdy version (`sudo howdy version`): 2.6.1

**Comment by boltgolt** [comment]
Seems like your dlib got compiled for the wrong cpu architecture, have you tried a reinstall?
