### ISSUE TITLE
Can howdy find the face using IR camera and using the depth parameters from the IR sensor or It already does?

### ISSUE THREAD

**Issue by BloodDrag0n** [boltgolt/howdy#718]
I don't know whether that howdy uses IR camera for dark area or for dark areas and depth detection to find the real human face, instead of cheating it with a human sized picture of myself. Does howdy have depth finding capability? 

If not, it would be a major security feature for howdy to detect the depth in the face and verify whether the face is real or 2D image, and additionally, creating a 3D model for the face with the facial feature points where both the normal and IR camera works together to find the face.

**Comment by boltgolt** [comment]
Howdy only compares known facial coordinates to faces found in a 2D video frame. Building the facial coordinates in 3D would obviously be better. However, it is very very difficult to implement in a way that is fast enough to keep the processed frames per second acceptable.

Using both the visual camera and IR camera is not possible for many devices, they only support one USB video stream
