### ISSUE TITLE
Immutable OS

### ISSUE THREAD

**Issue by thePretendend** [boltgolt/howdy#720]
OS: fedora Silverblue

Feature requested: Compatibility with Immutable OS.

I have noticed after installing howdy from copr repo on fedora 37 Silverblue, that this project seems incompatible with immutable OSs like Silverblue or probably MicroOs and others. After reading some of the code, I'd like to give this a try though I am very much not an experienced programmer. Maybe I can count on someones assistance here who has more experience and maybe knows the code.

From what I have read, only some directories locations need to be changed where data like config.ini and the facial models are stored to be in /etc/howdy for example instead of /lib64/security/howdy 

Thank's in advance.

**Comment by boltgolt** [comment]
Good idea, please take a look at #648
