### ISSUE TITLE
Low Light or bad lighting no face recognition

### ISSUE THREAD

**Issue by BigCityCat** [boltgolt/howdy#723]
This is an awesome program and really appreciate the work put in. Using Dell XPS with Ubuntu and Windows. I notice that windows facial unlock is turning on a light with the webcam to assist in low light or bad lighting situations to assist the camera. Is that possible with this application or is the feature not possible. That is really holding this application back. It really only works in perfect lighting conditions.

Well and also it doesn't open the key ring on login so you still have to type in your password. I know that the gnome devs won't allow it due to security reasons.

**Comment by boltgolt** [comment]
That works for almost everyone yes, are you sure you are using your IR camera and not the normal visible light webcam?

**Comment by BigCityCat** [comment]
Sorry I guess I was on the wrong camera. I changed it and it looks a lot more clear when I test it. It was on video2 but video0 is the correct camera.
