### ISSUE TITLE
cinnamon-screensaver do not trigger Howdy

### ISSUE THREAD

**Issue by lcseguin** [boltgolt/howdy#73]
When the screen is locked with [cinnamon-screensaver](/linuxmint/cinnamon-screensaver) Howdy is not triggered when the password is asked.

----

**Linux distribution (if applicable)**: Linuxmint 19.1
**Howdy version**: 2.3.0

**Comment by boltgolt** [comment]
Take a look at [this](https://github.com/boltgolt/howdy/issues/28#issuecomment-396231042) comment.

**Comment by lcseguin** [comment]
It's worked for me. Thanks :+1:
