### ISSUE TITLE
Tests pass, but doesn't work with any form of authentication

### ISSUE THREAD

**Issue by lucaliceti** [boltgolt/howdy#732]
_Please describe the issue in as much detail as possible, including any errors and traces._
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

Howdy doesn't work for anything authentication related, such as running a command with sudo, or signing in to gnome 42.
Running both `sudo howdy test` and `sudo howdy snapshot` works.

But howdy test returns:
`[ WARN:0@0.070] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0@0.070] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@0.070] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created`

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): 
- OS: Arch Linux x86_64
- Host: 81YM IdeaPad 5 14ARE05
- Kernel: 5.15.81-1-lts

Howdy version (`sudo howdy version`):
- Howdy 2.6.1

**Comment by captjay98** [comment]
Hello ,did you manage to get a fix?

**Comment by yi-ge** [comment]
I have the same problem.

**Comment by boltgolt** [comment]
I see you're on arch, have you added any lines to the PAM?

**Comment by lucaliceti** [comment]
Could you explained what you mean by PAM? I've never hear of that before. Thank you.

**Comment by boltgolt** [comment]
It's what regulates how authentication is done on the system. Did you use the arch wiki guide to install Howdy? That includes setting the right settings in PAM files

**Comment by musikid** [comment]
Closing this as it seems to be a misconfiguration problem. Feel free to reopen it if you don't agree.
