### ISSUE TITLE
Nothing has happend on Debian Testing

### ISSUE THREAD

**Issue by zsxboli** [boltgolt/howdy#742]
The installation process went smoothly.And sudo howdy test is good running.Everything is OK.But It does not seem to work.
In terminal,type "sudo  -i",I also need to enter passwd.More than that,in login interface and other scenarios that require password input,it does not work!

Linux distribution (if applicable):Debian Testing+Gnome

Howdy version (`sudo howdy version`):2.6.1

**Comment by boltgolt** [comment]
Did you run `sudo howdy add`?

**Comment by zsxboli** [comment]
> 

Ye.I am ready for everything.

**Comment by zsxboli** [comment]
> Did you run `sudo howdy add`?



> > 
> 
> Ye.I am ready for everything.

I had reinstalled my system,and then ,reinstalled howdy with gdebi.And did as https://github.com/boltgolt/howdy/issues/711#issuecomment-1306559496  (but on debian ,the 'pam.py' in /lib/security/howdy,so,I modified the path).

And then ,I did as https://github.com/boltgolt/howdy/issues/734#issuecomment-1349218211 ,modified the pam.py.And  sudo chmod +x /lib/security/howdy/pam.py.

Finally ,I successed.All running well.

**Comment by vmlinux26** [comment]
mine is running fine except for the screen unlock after the computer has been in sleep mode from closing laptop
running 'mate' 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"

**Comment by zsxboli** [comment]
> mine is running fine except for the screen unlock after the computer has been in sleep mode from closing laptop
> running 'mate' 
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> 
> edit "chmod +x /lib/security/howdy/pam.py"  doesn't work on mine

Maybe this problem is related to linux desktop environment.
I tried this measure on Gnome and succeed.

**Comment by Jung1ePeng** [comment]
> > mine is running fine except for the screen unlock after the computer has been in sleep mode from closing laptop
> > running 'mate'
> > PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> > edit "chmod +x /lib/security/howdy/pam.py"  doesn't work on mine
> 
> Maybe this problem is related to linux desktop environment. I tried this measure on Gnome and succeed.

After following the instructions here, everything worked fine. I also use Debian testing with GNOME. Before this, I referred to the [Arch Wiki](https://wiki.archlinux.org/title/Howdy) and add this to the sudo and gdm-password files:

>auth sufficient pam_unix.so try_first_pass likeauth nullok

And that makes a mistake for me, so just remove it, then everything works fine. It seems to be a difference between Arch and Debian.
