### ISSUE TITLE
Login Keyring is not getting unlocked

### ISSUE THREAD

**Issue by soumyatheman** [boltgolt/howdy#744]
**Everytime I unlock my ubuntu with howdy, I get an error everytime that my password keyring has not unlocked yet, I have to give my root password there again. Also howdy isn't showing up there.**

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): ubuntu 22.10

Howdy version (`sudo howdy version`): Howdy 2.6.1

**Comment by boltgolt** [comment]
Please search other issues before opening a new one, check out https://github.com/boltgolt/howdy/issues/438

**Comment by boltgolt** [comment]
If you're asking that then you clearly have not checked it
