### ISSUE TITLE
not installable using nala

### ISSUE THREAD

**Issue by Vosjedev** [boltgolt/howdy#753]
_Please describe the issue in as much detail as possible, including any errors and traces._  
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._  

If i try to install using sudo nala install howdy, it seams to hang at `starting certainty auto config`. 
I think this is because of nala's scrolling feature.

----

I've searched for similar issues already, and my issue has not been reported yet.

_Linux distribution (if applicable):_
all distro's using apt (when nala is installed and used)
_Howdy version (`sudo howdy version`):_
newest (does not matter, its in the installing)

putting a note under the installation instructions using apt should be fine.

**Comment by boltgolt** [comment]
The next version of Howdy no longer includes that install step, and nala does not seem like a widely used tool. User apt or dpkg for now
