### ISSUE TITLE
howdy while lid is closed

### ISSUE THREAD

**Issue by rogelioamancisidor** [boltgolt/howdy#763]
I have installed howdy and works perfectly. Most of the times, I work using external monitor and camera. If I specified the `device_path` to the external usb camera, `howdy` works fine using the usb external camera as long as the lid is opened (even though the laptop's monitor is off). 

How can I change this behavior and use the usb camera but with the lid closed? I have seen this question #515, which I think it suggests that it is possible to use `howdy` with external usb camera and closed lid. BTW, `HandleLidSwitch` is set to `ignore` in my `logind.conf` file.

**Comment by rogelioamancisidor** [comment]
I found out the option `ignore_closed_lid` in the configuration file. Setting it to `false` solves my problem.

**Comment by whowantsmybigdata** [comment]
added to wiki
