### ISSUE TITLE
Camera can only be read during installation setup

### ISSUE THREAD

**Issue by VermiIIi0n** [boltgolt/howdy#767]
Hi, I am using a Tobii 5 camera. During installation setup, it was turned on (When I was asked if the camera is working, I could see IR blinking), however later when I tried to add my face it no longer worked.

I have tried different `device_path` and different recording plugins but none of them worked.

I can't find the source code of that setup script, but that implementation seems working for me. Can anyone paste it here? Thanks.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution: Ubuntu 22.04

Howdy version (`sudo howdy version`): 2.6.1

**Comment by boltgolt** [comment]
You can find the [preinst script here](https://github.com/boltgolt/howdy/blob/master/debian/preinst), but in short is just reads input from all devices found in `/dev/v4l/by-path/` with streamer
