### ISSUE TITLE
pam_howdy freezes and causes calling programs to freeze

### ISSUE THREAD

**Issue by fufexan** [boltgolt/howdy#768]
When I try to authenticate through Howdy and it fails, the calling program (greetd or swaylock) freezes.
I originally thought it was a greetd issue, and opened an issue [here](https://todo.sr.ht/~kennylevinsen/greetd/41#event-230469). As discussed there, it turns out it is actually a `pam_howdy` bug.

- [x] I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): NixOS Stoat 23.05

Howdy version (`sudo howdy version`): `3.0.0 BETA`

**Comment by Catty2014** [comment]
Same issue here. `pam_howdy` causes sudo and KDE lock screen to crash.
It seems that pam_howdy threw an exception, making lockers to crash.

**Comment by SimonBrandner** [comment]
I can also repro and it's a showstopper for me since I don't want my KDE lock screen crashing on me if it can't detect me :/

**Comment by SimonBrandner** [comment]
I don't seem to be able to repro on `beta` anymore - can anyone reproduce? If not, I suggest closing this issue

**Comment by fufexan** [comment]
Right, it seems to work fine now. Closing.
