### ISSUE TITLE
Keyring is asking for password after login in Ubuntu 18.04

### ISSUE THREAD

**Issue by cccaballero** [boltgolt/howdy#77]
After I log in to session the gnome keyring ask for password, this is not too annoying for me because I rarely close my session or restart the laptop, but it makes howdy kind useless if you power off the PC or close your session a lot, because you need to type your password right after login anyway.

----

**Linux distribution**: Ubuntu
**Howdy version**: 2.3.1

**Comment by boltgolt** [comment]
Take a look at issue #39.
