### ISSUE TITLE
Howdy prevents typing password

### ISSUE THREAD

**Issue by BenMac31** [boltgolt/howdy#770]
When I use Howdy, I have to wait for Howdy to either identify my face or time out before I am able to begin typing the password. When Howdy identifies my face this works fine because I spend less time than I would typing, but if it does not I end up spending way more time waiting for howdy to finish then typing in my password.

System Arch Linux
Howdy 2.6.1

**Comment by boltgolt** [comment]
Implemented in 3.0.0 beta now, checkout the ninth issue ever: #9

**Comment by BenMac31** [comment]
Thanks! Sorry for bothering with this issue.
