### ISSUE TITLE
Problem with save

### ISSUE THREAD

**Issue by AzizBeaudelaire** [boltgolt/howdy#780]
Sorry I have a problem with howdy, when i use this command : "sudo howdy add" and choose a name for my save (after following installation), i have this error : 
Adding face model for the user hugo
Enter a label for this new model [Initial model] (max 24 characters): test
Camera path is not configured correctly, please edit the 'device_path' config value.
Exception ignored in: <function VideoCapture.__del__ at 0x7f604c6dac20>
Traceback (most recent call last):
  File "/usr/lib/security/howdy/recorders/video_capture.py", line 55, in __del__
    self.internal.release()
AttributeError: 'VideoCapture' object has no attribute 'internal'

Someone have an idea too help me pls.

Thanks
----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):

Howdy version (`sudo howdy version`):

**Comment by boltgolt** [comment]
From your output:
```
 Camera path is not configured correctly, please edit the 'device_path' config value.
```

https://github.com/boltgolt/howdy/wiki/Common-issues#error-when-trying-to-add-a-face-model
