### ISSUE TITLE
Add passkey webauthn and the option to use hardware keys (example yubikeys) in order to make the login process more secure.

### ISSUE THREAD

**Issue by Chummpp** [boltgolt/howdy#782]
Howdy seems to be the only facial recognition technology for mainstream use on Linux and it can easily be one of its best security tools. Howdy could make Linux more secure by making use of passkey webauthn. Also as a side note don't hold your breath for Ubuntu and all the other Linux OS/distro developers to implement facial recognition with passkey or any other form of passkey for that matter. The Linux OS/distro developers are either lazy when it comes to implementing security features for mainstream use or they don't really care about implementing security features when it comes to creating a os/distro for mainstream use.

**Comment by boltgolt** [comment]
Howdy is just a PAM module for face authentication. If you want to use another type (like fingerprint, or hardware keys) you need another PAM module for that. Most of what you're talking about already exists but is not installed by default

**Comment by Chummpp** [comment]
> Most of what you're talking about already exists but is not installed by default

If that's true than why is it not widely known, talked about, and not already pre installed for the user?

**Comment by boltgolt** [comment]
Can't say, i don't maintain any distros
