### ISSUE TITLE
Not being prompted to use face unlock

### ISSUE THREAD

**Issue by dnk-codes** [boltgolt/howdy#785]
I have recently updated my Ubuntu to the latest version 23.04. I had to fix some issues regarding missing `dlib` and `cv2` but that wasn't anything major.
The issue I currently have is that Howdy does not ask me for my face. I have checked the config and re-enabled howdy but I am only prompted to type in my password.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution: Ubuntu 23.04

Howdy version (`sudo howdy version`): 2.6.1

**Comment by okaits** [comment]
same on 23.04

**Comment by okaits** [comment]
python3.11's `ConfigParser` module seems to be renamed to `configparser`.
I changed `import ConfigParser` to `import configparser as ConfigParser`, then it worked.

```patch
--- /usr/lib/security/howdy/pam.py	2023-05-03 19:44:47.918862004 +0900
+++ /usr/lib/security/howdy/pam.py	2023-05-03 19:36:54.698717328 +0900
@@ -7,7 +7,8 @@
 import syslog
 
 # pam-python is running python 2, so we use the old module here
-import ConfigParser
+#import ConfigParser
+import configparser as ConfigParser
 
 # Read config from disk
 config = ConfigParser.ConfigParser()
```

**Comment by dnk-codes** [comment]
> python3.11's `ConfigParser` module seems to be renamed to `configparser`. I changed `import ConfigParser` to `import configparser as ConfigParser`, then it worked.
> 
> ```diff
> --- /usr/lib/security/howdy/pam.py	2023-05-03 19:44:47.918862004 +0900
> +++ /usr/lib/security/howdy/pam.py	2023-05-03 19:36:54.698717328 +0900
> @@ -7,7 +7,8 @@
>  import syslog
>  
>  # pam-python is running python 2, so we use the old module here
> -import ConfigParser
> +#import ConfigParser
> +import configparser as ConfigParser
>  
>  # Read config from disk
>  config = ConfigParser.ConfigParser()
> ```

This is indeed the solution!
