### ISSUE TITLE
Remove AUR maintainer request from the Readme

### ISSUE THREAD

**Issue by raspimana** [boltgolt/howdy#789]
All howdy related AUR packages have maintainers.

![image](https://github.com/boltgolt/howdy/assets/36178983/204a1874-1302-4460-8d5f-7f3f027352c9)

**Comment by tokox** [comment]
Not sure, but maybe these maintainers are temporary until real maintainer will be found?

**Comment by boltgolt** [comment]
It's simply that i have not found enough time to get the 3.0.0 push across the finish line but have been focusing the little time i spend on that, and not necessarily on the readme unfortunately. What should it say?

**Comment by musikid** [comment]
Feel free to reopen if you think that we should indeed change the notice.
