### ISSUE TITLE
unable to make pam use howdy

### ISSUE THREAD

**Issue by arthur19q3** [boltgolt/howdy#792]
i installed howdy and passed the howdy test successfully, the snapshot function works perfectly too,  and then i added the following line to the top of /etc/pam.d/sudo file

`auth 		sufficient 	pam_python.so	/lib/security/howdy/pam.py
`
but sudo still then asks passwd all the time.

anyone has a clue?

--------------------------------------
OS: Manjaro Linux x86_64
Host: Z390 UD
Kernel: 6.2.13-1-MANJARO
Uptime: 3 mins
Packages: 1655 (pacman), 53 (brew)
Shell: fish 3.6.1
Resolution: 3840x2160, 1920x1080
DE: Cinnamon 5.6.8
WM: Mutter (Muffin)
WM Theme: Mint-Y-Dark-Orange (Mint-Y)
Theme: Adwaita-dark [GTK2/3]
Icons: ePapirus [GTK2/3]
Terminal: alacritty
Terminal Font: FiraCode NF
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
Memory: 2163MiB / 32037MiB

**Comment by gautierlabarre** [comment]
Hello, did you figure it out ? I think I have the same issue

**Comment by arthur19q3** [comment]
> Hello, did you figure it out ? I think I have the same issue

probably check your Python version and if it is compatible with what's written there in the python script. sorry mate it's been a while and my memory's a bit vague.

**Comment by gautierlabarre** [comment]
It's ok, I figured it out, I had to modify some python file. It was another issue, don't remember which. Thanks :)

**Comment by arthur19q3** [comment]
care to share what did the trick?  we occasionally need to hop between distros in our company and Howdy would intetestingly trigger different errors when it doesn't work out of box.I recall it's usually something to do with the version though.

**Comment by gautierlabarre** [comment]
Sure the fix for me was this one : https://github.com/boltgolt/howdy/issues/785#issuecomment-1533002545

**Comment by arthur19q3** [comment]
> Sure the fix for me was this one : [#785 (comment)](https://github.com/boltgolt/howdy/issues/785#issuecomment-1533002545)

thanks mate, i have encountered this some time ago as well, fix was the same.
