### ISSUE TITLE
Indication of the used algorithm

### ISSUE THREAD

**Issue by luarpy** [boltgolt/howdy#793]
Hello everyone,

I am delighted with howdy software and how useful it's in my day to day life. There are times that it fails and although I don't have a camera with an infrared sensor it isn't a big hassle for me. Although I would like to facilitate code development for other engineers who also come from the image processing and facial recognition field.

My request is to know what is the algorithm used and if it is based on any research or study done. In case there is any paper, it would be convenient to add a link or reference to it to facilitate its study. I think that in this way we could improve the code responsible for processing and detecting the facial image for programmers who have that part of knowledge. In this way it could facilitate the search for a better algorithm or several algorithms to improve the software.

**Comment by musikid** [comment]
It uses algorithms from [dlib](http://dlib.net/).
