### ISSUE TITLE
Howdy don't work after Arch big update

### ISSUE THREAD

**Issue by smjt2000** [boltgolt/howdy#795]
Hi.
I'm not good in English.
after the big Arch update that Python updated from 3.10 to 3.11 which is for weeks ago, Howdy don't work anymore.
I got this error when I use sudo:
```
Traceback (most recent call last):
  File "/lib/security/howdy/compare.py", line 17, in <module>
    import dlib
  File "/usr/lib/python3.11/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ModuleNotFoundError: No module named '_dlib_pybind11'
Unknown error: 1

```
in login page I got `Unknown error: 1`

I tried to reinstall `pybind` and `dlib` but problem didn't solve.

Howdy version 2.6.1:
Distro: EndeavourOS

**Comment by smjt2000** [comment]
> Run `sudo pip install dlib`

I did this but it doesn't solve the problem.

**Comment by Jackaed** [comment]
Try `sudo pip install pybind11`

**Comment by smjt2000** [comment]
> Try `sudo pip install pybind11`

I did all of this and nothing.
I tried clean install with `yay` install packages with `sudo pip ...` or `pip install ... --user` but they don't solve the problem.

**Comment by tokox** [comment]
Never run these distros in my small life, but you could try to go back to previous versions of dlib/pybind11/howdy. From my small experience `dlib` always creates problems.

**Comment by musikid** [comment]
Did you try to install dlib from AUR?

**Comment by musikid** [comment]
Feel free to re-open if you can give more information.
