### ISSUE TITLE
Project Need to be Updated

### ISSUE THREAD

**Issue by 022UGDW213** [boltgolt/howdy#820]
ubuntu@O22UGDW213:~/Desktop/Git Hub Folders/howdy$ ls /dev/video*
/dev/video0   /dev/video11  /dev/video2  /dev/video5  /dev/video8
/dev/video1   /dev/video12  /dev/video3  /dev/video6  /dev/video9
/dev/video10  /dev/video13  /dev/video4  /dev/video7
ubuntu@O22UGDW213:~/Desktop/Git Hub Folders/howdy$ cat /var/log/syslog | grep camera
Jul 30 13:07:27 O22UGDW213 kernel: [  101.279786] ipu3-cio2 0000:00:14.3: Connected 1 cameras
Jul 30 13:07:32 O22UGDW213 systemd[1777]: Starting Virtual filesystem service - digital camera monitor...
Jul 30 13:07:32 O22UGDW213 systemd[1777]: Started Virtual filesystem service - digital camera monitor.
Jul 30 18:03:45 O22UGDW213 kernel: [   83.040346] ipu3-cio2 0000:00:14.3: Connected 1 cameras
Jul 30 18:03:51 O22UGDW213 systemd[1750]: Starting Virtual filesystem service - digital camera monitor...
Jul 30 18:03:51 O22UGDW213 systemd[1750]: Started Virtual filesystem service - digital camera monitor.
Jul 30 18:09:03 O22UGDW213 kernel: [   97.456166] ipu3-cio2 0000:00:14.3: Connected 1 cameras
Jul 30 18:09:08 O22UGDW213 systemd[1753]: Starting Virtual filesystem service - digital camera monitor...
Jul 30 18:09:08 O22UGDW213 systemd[1753]: Started Virtual filesystem service - digital camera monitor.
Jul 30 23:07:54 O22UGDW213 kernel: [  226.068639] ipu3-cio2 0000:00:14.3: Connected 1 cameras
Jul 30 23:07:59 O22UGDW213 systemd[1808]: Starting Virtual filesystem service - digital camera monitor...
Jul 30 23:07:59 O22UGDW213 systemd[1808]: Started Virtual filesystem service - digital camera monitor.
Jul 31 00:39:15 O22UGDW213 cheese[28832]: Device '/dev/video11' has no supported format: ../sys/v4l2/gstv4l2object.c(4039): gst_v4l2_object_set_format_full (): /GstCameraBin:camerabin/GstWrapperCameraBinSrc:camera_source/GstBin:bin18/GstV4l2Src:v4l2src1:#012Call to S_FMT failed for NV12 @ 4224x3136: Invalid argument
ubuntu@O22UGDW213:~/Desktop/Git Hub Folders/howdy$ grep "camera" /path/to/howdy.conf
sudo nano /path/to/howdy.conf
grep: /path/to/howdy.conf: No such file or directory
ubuntu@O22UGDW213:~/Desktop/Git Hub Folders/howdy$

**Comment by musikid** [comment]
Since there isn't anything wrong in the logs you provided, I am going to close the issue but feel free to re-open it if you have more information.
