### ISSUE TITLE
Howdy unlocked my PC (Ubuntu 22.04) using an image

### ISSUE THREAD

**Issue by ghaurii** [boltgolt/howdy#822]
I installed Howdy on **Ubuntu 22.04 LTS** and did all the config and was working fine.

I tested it out and was fine but I tested it out to see if it unlocks using my image which I took on my mobile.
I took a selfie and went to the login page on my pc (ubuntu 22.04). Then I hid my face and **showed the picture** on my webcam.

Unfortunately, it got unlocked and **is not secure.**

**Comment by boltgolt** [comment]
Did you read the bottom of the readme? Are you using an IR or visible light camera? Very difficult to get a phone screen to work when using a proper IR camera

**Comment by ghaurii** [comment]
I am using C922 PRO HD STREAM WEBCAM.
Link of the webcam:
https://www.logitech.com/en-us/products/webcams/c922-pro-stream-webcam.960-001087.html
