### ISSUE TITLE
Bypass first time configuration during apt install

### ISSUE THREAD

**Issue by rosydawn6** [boltgolt/howdy#823]
Hello.  First thank you for such a great FR login system.  It is very useful.  I am trying to automate the installation via a script and am wondering if there is a way to bypass the interactive prompts for configuration or pass in default values.  Ideally if they could be skipped I could use sed to put in the desired values after installation.

Thanks

**Comment by adamlove86** [comment]
I normally do 
echo f | sudo apt install python3 howdy -y

**Comment by rosydawn6** [comment]
Learn something new every day.  Great tip thanks!

**Comment by oxivanisher** [comment]
To anyone else finding this thread, the ubuntu ppa package file `preinst` checks for the `HOWDY_NO_PROMPT` environment variable. Set this variable to skip the setup.
