### ISSUE TITLE
Some problem when packaging howdy

### ISSUE THREAD

**Issue by xiangluoming** [boltgolt/howdy#826]
I'm trying to package this program on gentoo, but I have a problem: where should this program installed?
I refer to the package of archlinux, but it install all the source code to `/etc/howdy`, which is not a proper place according to FHS. I arbitrarily choose `/usr/lib/howdy` as the installation destination. But from the code in pam_howdy, it hardcode the path `/lib/security/howdy/compare.py`, which implies howdy should be installed in `/lib/security`. But some distribution have different preference on this directory, for example `/lib64/security`.
A possible solution is package howdy into a python package, because most distributions have mature process for packaging python packages. So that `pam_howdy.so` don't need to hardcode the path to `compare.py`.
Besides, the current code is looking for dlib model through the `config.ini` path. It means that `dlib-data` should be installed in `/etc/howdy`, which is not a good idea according to FHS. A candidate directory may be `/usr/share`. Now that it's external data comes from different repository, perhaps it's better to set the path in `config.ini`. This allows the packagers to choose the path suitable for their system, and users can use different models(for example, their own trained model).
The disadventage of these suggestions is that it breaks the existing packages, it's up to authors to weigh the pros and cons. I'm not a software developer, just a user new to packaging. Please point out if I don't think well.

**Comment by musikid** [comment]
Closed by #803.
