### ISSUE TITLE
Another feature request about disk usage

### ISSUE THREAD

**Issue by Trumeet** [boltgolt/howdy#86]
I'm using `apt` to install this software, but I saw there was a lot of dependents such as `CMake`, it may no longer needed after compiling and installing, remove these packages may reduce disk usages.
Thanks you for your great application!

**Comment by boltgolt** [comment]
Howdy depends on the python bindings for OpenCV 2 and on some Ubuntu installations (like mine for instance) the debian package installation for cv2 is corrupt. This means that if i require cv2 directly as a dependency, the installations affected by this problem are completely unable to install Howdy (broken dependency).

My fix at the time was to clone the underlying library during installation and to build it on the machine itself. This is why some direct dependencies of Howdy seem like they should be build dependencies. This "fix" isn't perfect however, and fails to properly bind to python in some instances (#32).

You're completely right that CMake should not be a direct dependency, but it's just a symptom of a larger problem. I'm going to close this, as i want #32 to be the main issue for this problem, but your point certainly stands.
