### ISSUE TITLE
Network icon has a question mark (?)

### ISSUE THREAD

**Issue by Dihfahsih1** [boltgolt/howdy#867]
I recently upgraded from Ubuntu 22 (jelly) to Ubuntu 23.4 lunar. Everything on my previous Ubuntu was working fine.

after the upgrade everything is working fine except only one, wifi, Ethernet connection and usb internet connection show a question mark when I connect.

is there a way I can fix this.

I have no way of using internet connection on Ubuntu 23, I have tried to use the recovery tool on boot but all the same no fix
Thanks

**Comment by boltgolt** [comment]
This is the issues page for Howdy, a face authentication program, not all of Ubuntu. There are better places to ask this. That being said: Have you tried resetting your network drivers?
