### ISSUE TITLE
test fail

### ISSUE THREAD

**Issue by udipta** [boltgolt/howdy#87]
The test window remains blank and does work. [
![screenshot from 2018-10-24 03-32-08](https://user-images.githubusercontent.com/28093579/47393551-73c3f880-d73d-11e8-8fb3-151912dacdc6.png)
](url)
$sudo howdy test

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x4600003
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x460000d

**Comment by boltgolt** [comment]
Please use the search function before opening a new issue. An open issue with this exact error and a solution can be found at #60. Your error is even in the title.

**Comment by udipta** [comment]
I'll keep in mind next time and thanks for the solution
