### ISSUE TITLE
Can not enroll on Ultramarine (Fedora)

### ISSUE THREAD

**Issue by TheOwenSZ** [boltgolt/howdy#872]
_Please describe the issue in as much detail as possible, including any errors and traces._
I cannot enroll under Ultramarine Linux, I am using the package from Copr
```
owen@owen:~$ sudo howdy add
[sudo] password for owen: 
Adding face model for the user owen
Enter a label for this new model [Initial model] (max 24 characters): owen
Camera path is not configured correctly, please edit the 'device_path' config value.
Exception ignored in: <function VideoCapture.__del__ at 0x7f46e5d9e520>
Traceback (most recent call last):
  File "/usr/lib64/security/howdy/recorders/video_capture.py", line 55, in __del__
    self.internal.release()
    ^^^^^^^^^^^^^
AttributeError: 'VideoCapture' object has no attribute 'internal'
```
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):

Howdy version (`sudo howdy version`):

**Comment by tokox** [comment]
@TheOwenSZ you have misconfigured your camera. Make sure device_path in config is correct. The error you see is occuring only when howdy exits with camera not opened, it isn't a problem.
