### ISSUE TITLE
Is this project still active ?

### ISSUE THREAD

**Issue by Vagrantin** [boltgolt/howdy#873]
Hello
I'm really interested by this project, also I don't see lot's of  activity and the latest release seems to be from Sept 3rd 2020..
hopefully I'm wrong and this is still an active project.

**Comment by tokox** [comment]
This is an active project and some people are still working on it. The planned release is 3.0.0, but it will be completely different: native pam module, translations etc. It is planned to be released once all of the big changes will be done. For current version just look at beta (default) branch.
