### ISSUE TITLE
Can't close test window with red x button

### ISSUE THREAD

**Issue by SiBurgmaier** [boltgolt/howdy#882]
I can't close the test window with the x button. I close and start, but a bit lower. 

The practical solution is to "CTLR+C" in the console. 

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):
Ubuntu LTS
Howdy version (`sudo howdy version`):
Howdy 3.0.0 BETA

**Comment by boltgolt** [comment]
With how OpenCV handles the preview window this is unfortunately indented behavior. The console will tell you to press Ctrl+C
