### ISSUE TITLE
Howdy-GTK not installed?

### ISSUE THREAD

**Issue by simonsays-techtalk** [boltgolt/howdy#883]
I installed howdy, it works fine from CLI. However I expected that Howdy-GTK installed as well (from ppa). But it didn't, how can I install this on Pop!OS?

I installed howdy 2.6.1

**Comment by tokox** [comment]
I don't think this old release contains howdy-gtk.

**Comment by simonsays-techtalk** [comment]
I did this: sudo add-apt-repository ppa:boltgolt/howdy
sudo apt update
sudo apt install howdy

How was I able to install this old version?

**Comment by tokox** [comment]
Latest release is 4 years old. If you want newer you need to install beta version (idk if it's in ppa). #873
