### ISSUE TITLE
/etc/alternatives notion doesn't exist in Arch, or anything besides Ubuntu/Debian

### ISSUE THREAD

**Issue by yassineim** [boltgolt/howdy#89]
howdy config should probably use something like $EDITOR

**Comment by boltgolt** [comment]
`$EDITOR` doesn't exist in Ubuntu though, i'm open for any suggestions that work on all distros

**Comment by yassineim** [comment]
/bin/nano ?

On 2 Nov 2018 13:42, "boltgolt" <notifications@github.com> wrote:

$EDITOR doesn't exist in Ubuntu though, i'm open for any suggestions that
work on all distros

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/boltgolt/howdy/issues/89#issuecomment-435364571>, or mute
the thread

**Comment by boltgolt** [comment]
That would hardcode nano as editor, even for Ubuntu users that have a different default. I'll add a check for `/etc/alternatives/editor` and run `/bin/nano` if it doesn't exist.

**Comment by KelleyMcChes** [comment]
Would it bee better to check whether the program is running on Arch or Ubuntu and then use /etc/alternatives or $EDITOR respectively. That way, people who either don't like nano or don't have nano installed can use it

**Comment by boltgolt** [comment]
Yeah, good point. I'll keep nano as fallback so it'll go: Try `/etc/alternatives` > try `$EDITOR` > run `/bin/nano/`.
