### ISSUE TITLE
Can we use howdy to LOCK a screen rather than unlock it?

### ISSUE THREAD

**Issue by BillyCroan** [boltgolt/howdy#897]
Follow me here.  I'm happy using passwords.  And I want to increase security.  When I log in, I'd like howdy to take note of what I look like that day.  And keep the camera on while I'm using the computer.  watch me continuously.  if I leave the frame at all, run a command.  if I'm gone for more than x seconds, run another command.  I'll use those commands to start a screen locker.

When I come back I will  unlock via password.  But this keeps me secure, even if I forget to lock my screen.

I might set the first command to play a small beep and run xtrlock.  if I return to camera view before x seconds has elapsed, then kill xtrlock or cause it to unlock.  but after x seconds, the normal screensaver starts, and howdy can exit.

When the screensaver unlocks, howdy starts up again and the cycle repeats.

**Comment by musikid** [comment]
It doesn't work like that, Howdy can only be used for locking.
