### ISSUE TITLE
Can't run howdy on Ubuntu 24.04

### ISSUE THREAD

**Issue by ibahnasy** [boltgolt/howdy#911]
_Please describe the issue in as much detail as possible, including any errors and traces._
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

After installing howdy from the Ubuntu PPA as described in the README, there is no command with the name `howd`:
```
# howdy
howdy: command not found
root@<hostname>:/usr/lib/security/howdy# which howdy
root@<hostname>:/usr/lib/security/howdy# 
``` 

Also when trying to run it manually:
```
root@<hostname>:/usr/lib/security/howdy# ./cli.py -U <myusername> add
Adding face model for the user neo
Enter a label for this new model [Initial model] (max 24 characters): test
Camera path is not configured correctly, please edit the 'device_path' config value.
Exception ignored in: <function VideoCapture.__del__ at 0x73c82cd60fe0>
Traceback (most recent call last):
  File "/usr/lib/security/howdy/recorders/video_capture.py", line 55, in __del__
    self.internal.release()
    ^^^^^^^^^^^^^
AttributeError: 'VideoCapture' object has no attribute 'internal'
```

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Ubuntu 24.04

Howdy version (`sudo howdy version`): 2.6.1

**Comment by tokox** [comment]
> Camera path is not configured correctly, please edit the 'device_path' config value.

Read it please.
