### ISSUE TITLE
Howdy doesn't work with PAM but works as sudo howdy test

### ISSUE THREAD

**Issue by TheHighGroundWins** [boltgolt/howdy#926]
Installed from AUR.
howdy used to work without much problems until recently with the deprecation of python2.

pam-python-git as well as pip install pam, both work with sudo howdy test.

pam file:
`auth sufficient pam_python3.so /lib/security/howdy/pam.py`
`auth sufficient pam_python.so /lib/security/howdy/pam.py`

both combinations were used with no success.

pam-python from aur fails to build.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Artix Linux

Howdy version (`sudo howdy version`): Howdy 2.6.1

**Comment by mabdiyan** [comment]
please solve this problem

**Comment by TheHighGroundWins** [comment]
Now pam is finally invoked, and the pam configuration for howdy beta is working, even though I am using howdy-git.

`auth sufficient /lib/security/pam_howdy.so`


However, I am now having a different issue with unsupported image type which is another issue that is open. #928
