### ISSUE TITLE
dose not work with kali on asus laptop and also on surface pro 9, please solve problems and update your program

### ISSUE THREAD

**Issue by mabdiyan** [boltgolt/howdy#929]
_Please describe the issue in as much detail as possible, including any errors and traces._
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

dose not work with kali on asus laptop and also on surface pro 9, please solve problems and update your program

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):

Howdy version (`sudo howdy version`):

**Comment by mabdiyan** [comment]
please update your program please ....

**Comment by fanzhuyifan** [comment]
How does it not work? Are you seeing any error messages?

**Comment by boltgolt** [comment]
This is not how you write an issue report, contributors can't magically know what's wrong for you
