### ISSUE TITLE
GUI popup upon trigger to seek for attention

### ISSUE THREAD

**Issue by littleblack111** [boltgolt/howdy#949]
like a notification or sth like polkit gui popup when its triggered

**Comment by boltgolt** [comment]
This is implemented in howdy-gtk if you can get that to work

**Comment by littleblack111** [comment]
instructions / rtfm by any chance?

**Comment by boltgolt** [comment]
Currently completely undocumented and in development hell so

**Comment by littleblack111** [comment]
does building it normally work?(howdy) like just installing the aur howdy-git

**Comment by boltgolt** [comment]
I honestly do not know, Howdy 3 already has the connections to the -gtk version set up, so as long as you can get the command `howdy-gtk` to work it should do it

**Comment by littleblack111** [comment]
still haven't been able to get it to work... is it more stable now? is there a config i need to enable?
