### ISSUE TITLE
libjxl 0.11 breack howdy beta

### ISSUE THREAD

**Issue by DragoonZ** [boltgolt/howdy#959]
Archlinux just update the libjxl to 0.11
this breaks howdy beta
have to manually link the so file and recompile
sudo ln -s /usr/lib/libjxl_threads.so /usr/lib/libjxl_threads.so.0.10

sudo ln -s /usr/lib/libjxl.so /usr/lib/libjxl.so.0.10

maybe consider using .so directly ?

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): Archlinux

Howdy version (`sudo howdy version`):Howdy 3.0.0 BETA

**Comment by DragoonZ** [comment]
nvm, recompile the python-dlib solve the problem

**Comment by Hamster1962** [comment]
Thanks, that fixed mine too.

**Comment by dsteppp** [comment]
Thanks, that's worked!

**Comment by saidsay-so** [comment]
> nvm, recompile the python-dlib solve the problem
