### ISSUE TITLE
pam_python has python 2 dependency

### ISSUE THREAD

**Issue by NoahHallows** [boltgolt/howdy#975]
Howdy has a python 2 dependency, I think in the pam_python  module. Howdy works correctly but cannot communicate with PAM because of this missing dependency and Arch removing python 2.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution Arch:

Howdy version (3.0.0 BETA):

**Comment by Laess3r** [comment]
My howdy installation fails competely. It's a brand new Fedora system. Looks like pam_python required python2, which is unsupported these days!

>  sudo dnf --refresh install howdy
> ...

> Failed to resolve the transaction:
Problem: package howdy-2.6.1-10.fc41.x86_64 from copr:copr.fedorainfracloud.org:principis:howdy requires pam_python, but none of the providers can be installed
  - conflicting requests
  - nothing provides libpython2.7.so.1.0()(64bit) needed by pam_python-1.0.8-4.fc41.x86_64 from copr:copr.fedorainfracloud.org:principis:howdy
You can try to add to command line:
  --skip-broken to skip uninstallable packages
